<p align="center"><img src="/images/logo.png" alt=""></p>
<h1 align="center">What the f*ck Python! üò±</h1>
<p align="center">C√πng kh√°m ph√° v√† t√¨m hi·ªÉu Python th√¥ng qua c√°c ƒëo·∫°n m√£ khi·∫øn b·∫°n b·∫•t ng·ªù.</p>


C√°c b·∫£n d·ªãch ti·∫øng n∆∞·ªõc ngo√†i kh√°c: [Ti·∫øng Trung ‰∏≠Êñá](https://github.com/leisurelicht/wtfpython-cn) | [Th√™m b·∫£n d·ªãch](https://github.com/satwikkansal/wtfpython/issues/new?title=Add%20translation%20for%20[LANGUAGE]&body=Expected%20time%20to%20finish:%20[X]%20weeks.%20I%27ll%20start%20working%20on%20it%20from%20[Y].)

B·∫°n c√≥ th·ªÉ tham kh·∫£o c√°c ƒëo·∫°n m√£ v·ªõi: [Ch·∫ø ƒë·ªô tr·ª±c quan](https://colab.research.google.com/github/satwikkansal/wtfpython/blob/master/irrelevant/wtf.ipynb) | [Giao di·ªán d√≤ng l·ªánh](https://pypi.python.org/pypi/wtfpython)


Python l√† m·ªôt ng√¥n ng·ªØ c·∫•p cao, v·ªõi c√°c m√£ ƒë∆∞·ª£c th√¥ng d·ªãch thay v√¨ bi√™n d·ªãch nh∆∞ c√°c ng√¥n ng·ªØ kh√°c nh∆∞ C hay Java. Python c√≥ r·∫•t nhi·ªÅu c√°c t√≠nh nƒÉng gi√∫p vi·ªác l·∫≠p tr√¨nh d·ªÖ d√†ng, thu·∫≠n ti·ªán. Tuy nhi√™n, c√°c ƒëo·∫°n m√£ vi·∫øt b·∫±ng Python th·ªânh tho·∫£ng cho ra k·∫øt qu·∫£ kh√¥ng r√µ r√†ng, g√¢y kh√≥ hi·ªÉu khi m·ªõi nh√¨n v√†o.


wtfpython ƒë∆∞·ª£c t·∫°o ra v·ªõi mong mu·ªën gi·∫£i th√≠ch ch√≠nh x√°c c√°ch ho·∫°t ƒë·ªông c·ªßa c√°c ƒëo·∫°n m√£ tho·∫°t nh√¨n kh√≥ hi·ªÉu v√† c√°c t√≠nh nƒÉng √≠t ƒë∆∞·ª£c bi·∫øt t·ªõi trong Python.


M·ªôt v√†i v√≠ d·ª• c√≥ th·ªÉ kh√¥ng l√†m b·∫°n qu√° ng·∫°c nhi√™n, tuy v·∫≠y b·∫°n s·∫Ω kh√°m ph√° ƒë∆∞·ª£c nh·ªØng ƒëi·ªÅu hay ho v·ªÅ Python m√† c√≥ th·ªÉ b·∫°n ch∆∞a t·ª´ng bi·∫øt t·ªõi. H·ªçc l·∫≠p tr√¨nh th√¥ng qua nh·ªØng v√≠ d·ª• nh∆∞ v·∫≠y gi√∫p b·∫°n hi·ªÉu s√¢u h∆°n nh·ªØng th·ª© n·∫±m b√™n trong c·ªßa m·ªôt ng√¥n ng·ªØ l·∫≠p tr√¨nh, khi ƒë√≥ b·∫°n s·∫Ω th·∫•y h·ª©ng th√∫ h∆°n trong qu√° tr√¨nh h·ªçc.


N·∫øu ƒë·ªôc gi·∫£ l√† m·ªôt l·∫≠p tr√¨nh vi√™n c√≥ th√¢m ni√™n, h√£y th·ª≠ th·ª©c m√¨nh v·ªõi c√°c ƒëo·∫°n m√£ s·∫Øp t·ªõi, c·ªë g·∫Øng l√†m ƒë√∫ng m·ªói th·ª≠ th√°ch ngay trong l·∫ßn ƒë·∫ßu ti√™n. ƒê·ªôc gi·∫£ c√≥ th·ªÉ ƒë√£ th·ª≠ qu·∫£ m·ªôt v√†i trong s·ªë c√°c b√†i to√°n tr∆∞·ªõc ƒë√≥, ƒë·ªçc v√† l√†m c√°c b√†i to√°n d∆∞·ªõi ƒë√¢y c√≥ th·ªÉ gi√∫p b·∫°n √¥n l·∫°i ch√∫ng.


PS: N·∫øu b·∫°n ƒë√£ ƒë·ªçc b√†i n√†y tr∆∞·ªõc ƒë√≥, b·∫°n c√≥ th·ªÉ mu·ªën xem nh·ªØng thay ƒë·ªïi m·ªõi [·ªü ƒë√¢y](https://github.com/satwikkansal/wtfpython/releases/).



N√†o ta b·∫Øt ƒë·∫ßu ...

# Nh·ªØng n·ªôi dung ch√≠nh
<!-- Generated using "markdown-toc -i README.md --maxdepth 3"-->

<!-- toc -->

- [C·∫•u tr√∫c c·ªßa c√°c v√≠ d·ª•](#structure-of-the-examples)
    + [‚ñ∂ Some fancy Title](#-some-fancy-title)
- [C√°ch s·ª≠ d·ª•ng](#usage)
- [üëÄ C√°c v√≠ d·ª•](#-examples)
  * [Section: Strain your brain!](#section-strain-your-brain)
    + [‚ñ∂ First things first! *](#-first-things-first-)
    + [‚ñ∂ Strings can be tricky sometimes](#-strings-can-be-tricky-sometimes)
    + [‚ñ∂ Be careful with chained operations](#-be-careful-with-chained-operations)
    + [‚ñ∂ How not to use `is` operator](#-how-not-to-use-is-operator)
    + [‚ñ∂ Hash brownies](#-hash-brownies)
    + [‚ñ∂ Deep down, we're all the same.](#-deep-down-were-all-the-same)
    + [‚ñ∂ Disorder within order *](#-disorder-within-order-)
    + [‚ñ∂ Keep trying... *](#-keep-trying-)
    + [‚ñ∂ For what?](#-for-what)
    + [‚ñ∂ Evaluation time discrepancy](#-evaluation-time-discrepancy)
    + [‚ñ∂ `is not ...` is not `is (not ...)`](#-is-not--is-not-is-not-)
    + [‚ñ∂ A tic-tac-toe where X wins in the first attempt!](#-a-tic-tac-toe-where-x-wins-in-the-first-attempt)
    + [‚ñ∂ The sticky output function](#-the-sticky-output-function)
    + [‚ñ∂ The chicken-egg problem *](#-the-chicken-egg-problem-)
    + [‚ñ∂ Subclass relationships](#-subclass-relationships)
    + [‚ñ∂ All-true-ation *](#-all-true-ation-)
    + [‚ñ∂ The surprising comma](#-the-surprising-comma)
    + [‚ñ∂ Strings and the backslashes](#-strings-and-the-backslashes)
    + [‚ñ∂ not knot!](#-not-knot)
    + [‚ñ∂ Half triple-quoted strings](#-half-triple-quoted-strings)
    + [‚ñ∂ What's wrong with booleans?](#-whats-wrong-with-booleans)
    + [‚ñ∂ Class attributes and instance attributes](#-class-attributes-and-instance-attributes)
    + [‚ñ∂ Non-reflexive class method *](#-non-reflexive-class-method-)
    + [‚ñ∂ yielding None](#-yielding-none)
    + [‚ñ∂ Yielding from... return! *](#-yielding-from-return-)
    + [‚ñ∂ Nan-reflexivity *](#-nan-reflexivity-)
    + [‚ñ∂ Mutating the immutable!](#-mutating-the-immutable)
    + [‚ñ∂ The disappearing variable from outer scope](#-the-disappearing-variable-from-outer-scope)
    + [‚ñ∂ The mysterious key type conversion](#-the-mysterious-key-type-conversion)
    + [‚ñ∂ Let's see if you can guess this?](#-lets-see-if-you-can-guess-this)
  * [Section: Slippery Slopes](#section-slippery-slopes)
    + [‚ñ∂ Modifying a dictionary while iterating over it](#-modifying-a-dictionary-while-iterating-over-it)
    + [‚ñ∂ Stubborn `del` operation](#-stubborn-del-operation)
    + [‚ñ∂ The out of scope variable](#-the-out-of-scope-variable)
    + [‚ñ∂ Deleting a list item while iterating](#-deleting-a-list-item-while-iterating)
    + [‚ñ∂ Lossy zip of iterators *](#-lossy-zip-of-iterators-)
    + [‚ñ∂ Loop variables leaking out!](#-loop-variables-leaking-out)
    + [‚ñ∂ Beware of default mutable arguments!](#-beware-of-default-mutable-arguments)
    + [‚ñ∂ Catching the Exceptions](#-catching-the-exceptions)
    + [‚ñ∂ Same operands, different story!](#-same-operands-different-story)
    + [‚ñ∂ Name resolution ignoring class scope](#-name-resolution-ignoring-class-scope)
    + [‚ñ∂ Needles in a Haystack *](#-needles-in-a-haystack-)
    + [‚ñ∂ Splitsies *](#-splitsies-)
    + [‚ñ∂ Wild imports *](#-wild-imports-)
    + [‚ñ∂ All sorted? *](#-all-sorted-)
    + [‚ñ∂ Midnight time doesn't exist?](#-midnight-time-doesnt-exist)
  * [Section: The Hidden treasures!](#section-the-hidden-treasures)
    + [‚ñ∂ Okay Python, Can you make me fly?](#-okay-python-can-you-make-me-fly)
    + [‚ñ∂ `goto`, but why?](#-goto-but-why)
    + [‚ñ∂ Brace yourself!](#-brace-yourself)
    + [‚ñ∂ Let's meet Friendly Language Uncle For Life](#-lets-meet-friendly-language-uncle-for-life)
    + [‚ñ∂ Even Python understands that love is complicated](#-even-python-understands-that-love-is-complicated)
    + [‚ñ∂ Yes, it exists!](#-yes-it-exists)
    + [‚ñ∂ Ellipsis *](#-ellipsis-)
    + [‚ñ∂ Inpinity](#-inpinity)
    + [‚ñ∂ Let's mangle](#-lets-mangle)
  * [Section: Appearances are deceptive!](#section-appearances-are-deceptive)
    + [‚ñ∂ Skipping lines?](#-skipping-lines)
    + [‚ñ∂ Teleportation](#-teleportation)
    + [‚ñ∂ Well, something is fishy...](#-well-something-is-fishy)
  * [Section: Miscellaneous](#section-miscellaneous)
    + [‚ñ∂ `+=` is faster](#--is-faster)
    + [‚ñ∂ Let's make a giant string!](#-lets-make-a-giant-string)
    + [‚ñ∂ Minor Ones *](#-minor-ones-)
- [Contributing](#contributing)
- [Acknowledgements](#acknowledgements)
- [üéì License](#-license)
  * [Surprise your friends as well!](#surprise-your-friends-as-well)
  * [More content like this?](#more-content-like-this)

<!-- tocstop -->

# C·∫•u tr√∫c c·ªßa c√°c v√≠ d·ª•

T·∫•t c·∫£ c√°c c√°c v√≠ d·ª• ƒë∆∞·ª£c tr√¨nh b√†y v·ªõi c·∫•u tr√∫c nh∆∞ sau:
> ### ‚ñ∂ M·ªôt ti√™u ƒë·ªÅ h·∫•p d·∫´n
>
> ```py
> # ƒêo·∫°n m√£ t·∫°o d·ª±ng v√≠ d·ª•.
> # ƒêo·∫°n m√£ ch·ªß th·ªÉ c·∫ßn kh√°m ph√°...
> ```
>
> **K·∫øt qu·∫£ (C√°c phi√™n b·∫£n Python):**
>
> ```py
> >>> c√¢u l·ªánh k√≠ch ho·∫°t?
> M·ªôt v√†i k·∫øt qu·∫£ b·∫•t ng·ªù, kh√¥ng nh∆∞ mong ƒë·ª£i
> ```
> (C√≥ th·ªÉ c√≥ hay kh√¥ng): M·ªôt d√≤ng m√¥ t·∫£ k·∫øt qu·∫£
>
>
> #### üí° Gi·∫£i th√≠ch:
>
> * Gi·∫£i th√≠ch nh·ªØng ƒëi·ªÅu ƒëang di·ªÖn ra v√† t·∫°i sao.
> ```py
> # ƒêo·∫°n m√£ t·∫°o d·ª±ng v√≠ d·ª•
> # Trong tr∆∞·ªùng h·ª£p c·∫ßn thi·∫øt, ch√∫ng t√¥i li·ªát k√™ th√™m nhi·ªÅu v√≠ d·ª• kh√°c ƒë·ªÉ gi√∫p b·∫°n hi·ªÉu r√µ h∆°n
> ```
> **K·∫øt qu·∫£ (C√°c phi√™n b·∫£n Python):**
>
> ```py
> >>> trigger # some example that makes it easy to unveil the magic
> >>> trigger # M·ªôt v√†i v√≠ d·ª• gi√∫p b·∫°n hi·ªÉu c√°c ƒëo·∫°n m√£
> # some justified output
> ```

**L∆∞u √Ω:** T·∫•t c·∫£ c√°c v√≠ d·ª• ƒë√£ ƒë∆∞·ª£c ch·ª©ng minh ch·∫°y th√†nh c√¥ng tr√™n tr√¨nh th√¥ng d·ªãch Python 3.5.2 ch·∫ø ƒë·ªô t∆∞∆°ng t√°c, v·ªõi c√°c phi√™n b·∫£n Python kh√°c c√°c v√≠ d·ª• s·∫Ω v·∫´n ch·∫°y b√¨nh th∆∞·ªùng, ngo·∫°i tr·ª´ m·ªôt s·ªë v√≠ d·ª• ch√∫ng t√¥i s·∫Ω l∆∞u √Ω tr∆∞·ªõc ph·∫ßn k·∫øt qu·∫£.
# C√°ch d√πng c√°c v√≠ d·ª•

Theo t√¥i, ƒë·ªÉ h·ªçc c√°c v√≠ d·ª• trong b√†i, b·∫°n n√™n ƒë·ªçc theo tr√¨nh t·ª± th·ªùi gian, v√† ƒë·ªëi v·ªõi m·ªói v√≠ d·ª• h√£y:
- ƒê·ªçc kƒ© ƒëo·∫°n m√£ t·∫°o d·ª±ng n√™n v√≠ d·ª•. N·∫øu b·∫°n ƒë√£ l·∫≠p tr√¨nh l√¢u r·ªìi, b·∫°n s·∫Ω ƒëo√°n ƒë∆∞·ª£c nh·ªØng ƒëi·ªÅu s·∫Øp t·ªõi ngay.
- ƒê·ªçc k·∫øt qu·∫£ c·ªßa c√°c v√≠ d·ª• v√† th·ª±c hi·ªán hai vi·ªác sau:
  + Ki·ªÉm tra xem k·∫øt qu·∫£ c√≥ gi·ªëng nh∆∞ b·∫°n nghƒ© hay kh√¥ng.
  + M·ªôt khi ƒë·ªçc xong, h√£y h·ªèi ch√≠nh b·∫°n xem m√¨nh ƒë√£ hi·ªÉu th√¥ng su·ªët l√Ω do m√† c√≥ k·∫øt qu·∫£ nh∆∞ v·∫≠y ch∆∞a.
    - N·∫øu c√¢u tr·∫£ l·ªùi l√† "ch∆∞a, t√¥i ch∆∞a hi·ªÉu" (kh√¥ng sao c·∫£), h√≠t m·ªôt h∆°i th·∫≠t sau, v√† ƒë·ªçc ph·∫ßn gi·∫£i th√≠ch (n·∫øu b·∫°n v·∫´n ch∆∞a hi·ªÉu, h√£y t·∫°o m·ªôt issue [·ªü d√¢y](https://github.com/satwikkansal/wtfpython/issues/new)).
    - N·∫øu c√¢u tr·∫£ l·ªùi l√† "c√≥, t√¥i ƒë√£ hi·ªÉu", b·∫°n c√≥ th·ªÉ ƒë·ªçc v√≠ d·ª• ti·∫øp theo.
PS: B·∫°n c√≥ th·ªÉ ƒë·ªçc WTFPython d√πng ch·∫ø ƒë·ªô d√≤ng l·ªánh s·ª≠ d·ª•ng [pypi package](https://pypi.python.org/pypi/wtfpython),
```sh
$ pip install wtfpython -U
$ wtfpython
```
---

# üëÄ C√°c v√≠ d·ª•

## Ch∆∞∆°ng 1: Hack n√£o!

### ‚ñ∂ M√≥n khai v·ªã! *

<!-- Example ID: d3d73936-3cf1-4632-b5ab-817981338863 -->
<!-- read-only -->

For some reason, the Python 3.8's "Walrus" operator (`:=`) has become quite popular. Let's check it out,
K√≠ hi·ªáu "con h√† m√£" ("Walrus" operator), ƒë∆∞·ª£c gi·ªõi thi·ªáu trong phi√™n b·∫£n Python 3.8 ƒë√£ tr·ªü n√™n kh√° ph·ªï bi·∫øn v√¨ m·ªôt v√†i l√Ω do. H√£y th·ª≠ qua n√≥ xem
1\.

```py
# Phi√™n b·∫£n Python 3.8+

>>> a = "wtf_walrus"
>>> a
'wtf_walrus'

>>> a := "wtf_walrus"
File "<stdin>", line 1
    a := "wtf_walrus"
      ^
SyntaxError: invalid syntax (L·ªói v·ªÅ c√∫ ph√°p: C√∫ ph√°p kh√¥ng h·ª£p l·ªá)

>>> (a := "wtf_walrus") # This works though
>>> a
'wtf_walrus'
```

2 \.

```py
# Phi√™n b·∫£n Python 3.8+

>>> a = 6, 9
>>> a
(6, 9)

>>> (a := 6, 9)
>>> a
6

>>> a, b = 6, 9 # Ph√¢n r√£ (unpacking) c√°c gi√° tr·ªã, hay c√≤n g·ªçi l√† c√¢u l·ªánh g√°n ƒëa gi√° tr·ªã (multiple assignments)
>>> a, b
(6, 9)
>>> (a, b = 16, 19) # C√≥ 
  File "<stdin>", line 1
    (a, b = 6, 9)
          ^
SyntaxError: invalid syntax (L·ªói c√∫ ph√°p: c√∫ ph√°p kh√¥ng h·ª£p l·ªá)

>>> (a, b := 16, 19) # C√¢u l·ªánh n√†y in ra m·ªôt tuple c√≥ 3 ph·∫ßn t·ª≠ kh√¥ng nh∆∞ mong ƒë·ª£i (ƒë√°ng l·∫Ω l√† 2 ph·∫ßn t·ª≠ 16 v√† 19)
(6, 16, 19)

>>> a # a ƒë∆∞·ª£c ƒë∆∞·ª£c g√°n l·∫°i gi√° tr·ªã tr∆∞·ªõc ƒë√≥, nh∆∞ng gi√° tr·ªã ph√≠a d∆∞·ªõi v·∫´n gi·ªØ nguy√™n, l√† sao?
6

>>> b 
16
```



#### üí° Gi·∫£i th√≠ch

**√în l·∫°i m·ªôt ch√∫t v·ªÅ k√≠ hi·ªáu "con h√† m√£"**

K√≠ hi·ªáu con h√† m√£ (`:=`) l·∫ßn ƒë·∫ßu ti√™n ƒë∆∞·ª£c gi·ªõi thi·ªáu trong phi√™n b·∫£n Python 3.8, n√≥ h·ªØu d·ª•ng khi b·∫°n mu·ªën g√°n gi√° tr·ªã cho c√°c bi·∫øn b√™n trong m·ªôt bi·ªÉu di·ªÖn (expression).

```py
def some_func():
        # Gi·∫£ ƒë·ªãnh r·∫±ng ta th·ª±c hi·ªán m·ªôt v√†i ph√©p t√≠nh t·ªën nhi·ªÅu t√†i nguy√™n (th·ªùi gian, I/O) ·ªü ƒë√¢y
        # time.sleep(1000)
        return 5

# Thay v√¨ th·ª±c hi·ªán vi·ªác ki·ªÉm tra k·∫øt qu·∫£ tr·∫£ v·ªÅ c·ªßa h√†m tr√™n,
if some_func():
        print(some_func()) # V√† g·ªçi l·∫°i h√†m ƒë√≥ trong th√¢n ƒëi·ªÅu ki·ªán, nghƒ©a l√† th·ª±c hi·ªán c√°c t√≠nh to√°n trong h√†m 2 l·∫ßn.
# Hay t·ªët h∆°n, ta c√≥ th·ªÉ ti·∫øt ki·ªám m·ªôt l·ªùi g·ªçi h√†m th√¥ng qua vi·ªác l·∫•y v·ªÅ gi√° tr·ªã tr·∫£ v·ªÅ ·ªü m·ªôt l·∫ßn g·ªçi v√† th·ª±c hi·ªán so s√°nh tr√™n gi√° tr·ªã ƒë√≥:
a = some_func()
if a:
    print(a)

# D√πng kƒ© hi·ªáu con h√† m√£ b·∫°n c√≥ th·ªÉ vi·∫øt ng·∫Øn g·ªçn h∆°n nh∆∞ d∆∞·ªõi ƒë√¢y, ph√©p g√°n ƒë∆∞·ª£c s·ª≠ d·ª•ng nh∆∞ m·ªánh ƒë·ªÅ ƒëi·ªÅu ki·ªán v√† ta c√≥ th·ªÉ s·ª≠ d·ª•ng bi·∫øn ƒë∆∞·ª£c g√°n gi√° tr·ªã trong th√¢n c√¢u ƒëi·ªÅu ki·ªán if:
if a := some_func():
        print(a)
```

**K·∫øt qu·∫£ (> 3.8):**

```py
5
5
5
```

S·ª≠ d·ª•ng k√≠ hi·ªáu con h√† m√£ gi√∫p ta r√∫t ng·∫Øn ƒë∆∞·ª£c ƒëo·∫°n m√£ ƒëi m·ªôt d√≤ng v√† tr√°nh ƒë∆∞·ª£c vi·ªác g·ªçi `some_func` hai l·∫ßn.
  
- Ta ch·ªâ ƒë∆∞·ª£c s·ª≠ d·ª•ng ph√©p g√°n c√≥ k√≠ hi·ªáu h√† m√£ ·ªü c·∫•p ƒë·ªô cao nh·∫•t do ƒë√≥ l·ªói c√∫ ph√°p (`SyntaxError`) trong c√¢u l·ªánh `a := "wtf_walrus"` x·∫£y ra. Khi ta cho ph√©p g√°n n√†y v√†o hai d·∫•u ngo·∫∑c ƒë∆°n `()` th√¨ s·∫Ω kh√¥ng b·ªã l·ªói n·ªØa.  

- Th√¥ng th∆∞·ªùng, c√¢u l·ªánh c√≥ d·∫•u b·∫±ng `=` s·∫Ω kh√¥ng ƒë∆∞·ª£c ph√©p ƒë·∫∑t trong d·∫•u ngo·∫∑c ƒë∆°n. Do v·∫≠y c√¢u l·ªánh `(a, b = 6, 9)` b·ªã l·ªói c√∫ ph√°p. 

- The syntax of the Walrus operator is of the form `NAME:= expr`, where `NAME` is a valid identifier, and `expr` is a valid expression. Hence, iterable packing and unpacking are not supported which means, 

- C√∫ ph√°p c·ªßa k√≠ hi·ªáu g√°n con h√† m√£ nh∆∞ sau: `NAME:= expr`, ·ªü ƒë√≥ `NAME` l√† m·ªôt t√™n bi·∫øn h·ª£p l·ªá, v√† `expr` l√† m·ªôt bi·ªÉu di·ªÖn h·ª£p l·ªá. Do v·∫≠y, vi·ªác s·ª≠ d·ª•ng c√°c ph√©p g·ªôp (packing) hay ph√¢n r√£ trong tr∆∞·ªùng h·ª£p n√†y s·∫Ω kh√¥ng ƒë∆∞·ª£c h·ªó tr·ª£, ngh√£i l√† 
  - `(a := 6, 9)` t∆∞∆°ng ƒë∆∞∆°ng v·ªõi `((a := 6), 9)` v√† bu·ªïi di·ªÖn cu·ªëi c√πng l√†  `(a, 9) ` (·ªü ƒë√≥ gi√° tr·ªã c·ªßa  `a` l√† 6). B·∫°n c√≥ th·ªÉ ki·ªÉm tra l·∫°i v·ªõi c√°c d√≤ng l·ªánh d∆∞·ªõi ƒë√¢y

    ```py
    >>> (a := 6, 9) == ((a := 6), 9)
    True # Bi·ªÉu di·ªÖn b√™n tr√°i b·∫±ng b√™n ph·∫£i do ph√©p ph√¢n r√£ kh√¥ng ƒë∆∞·ª£c ph√©p (nh∆∞ ƒë√£ gi·∫£i th√≠ch ph√≠a tr√™n)
    >>> x = (a := 696, 9)
    >>> x
    (696, 9)
    >>> x[0] is a # C·∫£ x[0] v√† a c√πng tr·ªè v·ªÅ chung m·ªôt ƒë·ªãa ch·ªâ trong b·ªô nh·ªõ 
    True
    ```

  - T∆∞∆°ng t·ª±, `(a, b := 16, 19)` t∆∞∆°ng ƒë∆∞∆°ng v·ªõi `(a, (b := 16), 19)` khi ta c√≥ 3 gi√° tr·ªã trong m·ªôt tuple. 

---

### ‚ñ∂ Strings th·ªânh tho·∫£ng c√≥ th·ªÉ kh√° o√°i oƒÉm

<!-- Example ID: 30f1d3fc-e267-4b30-84ef-4d9e7091ac1a --->
1\.

```py
>>> a = "some_string"
>>> id(a)
140420665652016
>>> id("some" + "_" + "string") # ƒê·ªÉ √Ω r·∫±ng c·∫£ hai gi√° tr·ªã id ƒë·ªÅu gi·ªëng nhau (140420665652016).
140420665652016
```

2\.
```py
>>> a = "wtf"
>>> b = "wtf"
>>> a is b
True # a v√† b c√πng tr·ªè t·ªõi m·ªôt ƒë·ªãa ch·ªâ trong b·ªô nh·ªõ

>>> a = "wtf!"
>>> b = "wtf!"
>>> a is b
False # a v√† b kh√¥ng c√πng tr·ªè t·ªõi m·ªôt ƒë·ªãa ch·ªâ trong b·ªô nh·ªõ

```

3\.

```py
>>> a, b = "wtf!", "wtf!"
>>> a is b # √Åp d·ª•ng cho t·∫•t c·∫£ c√°c phi√™n b·∫£n Python, ngo·∫°i tr·ª´ c√°c phi√™n b·∫£n 3.7.x
True # a v√† b c√πng tr·ªè t·ªõi m·ªôt ƒë·ªãa ch·ªâ trong b·ªô nh·ªõ

>>> a = "wtf!"; b = "wtf!"
>>> a is b # K·∫øt qu·∫£ l√† True ho·∫∑c False tu·ª≥ thu·ªôc v√†o m√¥i tr∆∞·ªùng b√™n ch·∫°y ƒëo·∫°n m√£ (python shell / ipython / as a script)
False
```

```py
# T·∫°o m·ªôt file t√™n some_file.py, ch·ª©a ba d√≤ng code d∆∞·ªõi ƒë√¢y:
a = "wtf!"
b = "wtf!"
print(a is b)

# Khi file n√†y ƒë∆∞·ª£c ch·∫°y k·∫øt qu·∫£ in ra l√† True

```

4\.

**K·∫øt qu·∫£ (< Python3.7 )**

```py
>>> 'a' * 20 is 'aaaaaaaaaaaaaaaaaaaa'
True
>>> 'a' * 21 is 'aaaaaaaaaaaaaaaaaaaaa'
False
```

C√≥ g√¨ ƒë√≥ sai sai?

#### üí° Explanation:
+ The behavior in first and second snippets is due to a CPython optimization (called string interning) that tries to use existing immutable objects in some cases rather than creating a new object every time.
+ After being "interned," many variables may reference the same string object in memory (saving memory thereby).
+ In the snippets above, strings are implicitly interned. The decision of when to implicitly intern a string is implementation-dependent. There are some rules that can be used to guess if a string will be interned or not:
  * All length 0 and length 1 strings are interned.
  * Strings are interned at compile time (`'wtf'` will be interned but `''.join(['w', 't', 'f'])` will not be interned)
  * Strings that are not composed of ASCII letters, digits or underscores, are not interned. This explains why `'wtf!'` was not interned due to `!`. CPython implementation of this rule can be found [here](https://github.com/python/cpython/blob/3.6/Objects/codeobject.c#L19)
  ![image](/images/string-intern/string_intern.png)
+ When `a` and `b` are set to `"wtf!"` in the same line, the Python interpreter creates a new object, then references the second variable at the same time. If you do it on separate lines, it doesn't "know" that there's already `"wtf!"` as an object (because `"wtf!"` is not implicitly interned as per the facts mentioned above). It's a compile-time optimization. This optimization doesn't apply to 3.7.x versions of CPython (check this [issue](https://github.com/satwikkansal/wtfpython/issues/100) for more discussion).
+ A compile unit in an interactive environment like IPython consists of a single statement, whereas it consists of the entire module in case of modules. `a, b = "wtf!", "wtf!"` is single statement, whereas `a = "wtf!"; b = "wtf!"` are two statements in a single line. This explains why the identities are different in `a = "wtf!"; b = "wtf!"`, and also explain why they are same when invoked in `some_file.py`
+ The abrupt change in the output of the fourth snippet is due to a [peephole optimization](https://en.wikipedia.org/wiki/Peephole_optimization) technique known as Constant folding. This means the expression `'a'*20` is replaced by `'aaaaaaaaaaaaaaaaaaaa'` during compilation to save a  few clock cycles during runtime. Constant folding only occurs for strings having a length of less than 20. (Why? Imagine the size of `.pyc` file generated as a result of the expression `'a'*10**10`). [Here's](https://github.com/python/cpython/blob/3.6/Python/peephole.c#L288) the implementation source for the same.
+ Note: In Python 3.7, Constant folding was moved out from peephole optimizer to the new AST optimizer with some change in logic as well, so the fourth snippet doesn't work for Python 3.7. You can read more about the change [here](https://bugs.python.org/issue11549). 

---


### ‚ñ∂ Be careful with chained operations
<!-- Example ID: 07974979-9c86-4720-80bd-467aa19470d9 --->
```py
>>> (False == False) in [False] # makes sense
False
>>> False == (False in [False]) # makes sense
False
>>> False == False in [False] # now what?
True

>>> True is False == False
False
>>> False is False is False
True

>>> 1 > 0 < 1
True
>>> (1 > 0) < 1
False
>>> 1 > (0 < 1)
False
```

#### üí° Explanation:

As per https://docs.python.org/2/reference/expressions.html#not-in

> Formally, if a, b, c, ..., y, z are expressions and op1, op2, ..., opN are comparison operators, then a op1 b op2 c ... y opN z is equivalent to a op1 b and b op2 c and ... y opN z, except that each expression is evaluated at most once.

While such behavior might seem silly to you in the above examples, it's fantastic with stuff like `a == b == c` and `0 <= x <= 100`.

* `False is False is False` is equivalent to `(False is False) and (False is False)`
* `True is False == False` is equivalent to `True is False and False == False` and since the first part of the statement (`True is False`) evaluates to `False`, the overall expression evaluates to `False`.
* `1 > 0 < 1` is equivalent to `1 > 0 and 0 < 1` which evaluates to `True`.
* The expression `(1 > 0) < 1` is equivalent to `True < 1` and
  ```py
  >>> int(True)
  1
  >>> True + 1 #not relevant for this example, but just for fun
  2
  ```
  So, `1 < 1` evaluates to `False`

---

### ‚ñ∂ How not to use `is` operator
<!-- Example ID: 230fa2ac-ab36-4ad1-b675-5f5a1c1a6217 --->
The following is a very famous example present all over the internet.

1\.

```py
>>> a = 256
>>> b = 256
>>> a is b
True

>>> a = 257
>>> b = 257
>>> a is b
False
```

2\.

```py
>>> a = []
>>> b = []
>>> a is b
False

>>> a = tuple()
>>> b = tuple()
>>> a is b
True
```

3\.
**Output**

```py
>>> a, b = 257, 257
>>> a is b
True
```

**Output (Python 3.7.x specifically)**

```py
>>> a, b = 257, 257
>> a is b
False
```

#### üí° Explanation:

**The difference between `is` and `==`**

* `is` operator checks if both the operands refer to the same object (i.e., it checks if the identity of the operands matches or not).
* `==` operator compares the values of both the operands and checks if they are the same.
* So `is` is for reference equality and `==` is for value equality. An example to clear things up,
  ```py
  >>> class A: pass
  >>> A() is A() # These are two empty objects at two different memory locations.
  False
  ```

**`256` is an existing object but `257` isn't**

When you start up python the numbers from `-5` to `256` will be allocated. These numbers are used a lot, so it makes sense just to have them ready.

Quoting from https://docs.python.org/3/c-api/long.html
> The current implementation keeps an array of integer objects for all integers between -5 and 256, when you create an int in that range you just get back a reference to the existing object. So it should be possible to change the value of 1. I suspect the behavior of Python, in this case, is undefined. :-)

```py
>>> id(256)
10922528
>>> a = 256
>>> b = 256
>>> id(a)
10922528
>>> id(b)
10922528
>>> id(257)
140084850247312
>>> x = 257
>>> y = 257
>>> id(x)
140084850247440
>>> id(y)
140084850247344
```

Here the interpreter isn't smart enough while executing `y = 257` to recognize that we've already created an integer of the value `257,` and so it goes on to create another object in the memory.

Similar optimization applies to other **immutable** objects like empty tuples as well. Since lists are mutable, that's why `[] is []` will return `False` and `() is ()` will return `True`. This explains our second snippet. Let's move on to the third one, 

**Both `a` and `b` refer to the same object when initialized with same value in the same line.**

**Output**

```py
>>> a, b = 257, 257
>>> id(a)
140640774013296
>>> id(b)
140640774013296
>>> a = 257
>>> b = 257
>>> id(a)
140640774013392
>>> id(b)
140640774013488
```

* When a and b are set to `257` in the same line, the Python interpreter creates a new object, then references the second variable at the same time. If you do it on separate lines, it doesn't "know" that there's already `257` as an object.

* It's a compiler optimization and specifically applies to the interactive environment. When you enter two lines in a live interpreter, they're compiled separately, therefore optimized separately. If you were to try this example in a `.py` file, you would not see the same behavior, because the file is compiled all at once. This optimization is not limited to integers, it works for other immutable data types like strings (check the "Strings are tricky example") and floats as well,

  ```py
  >>> a, b = 257.0, 257.0
  >>> a is b
  True
  ```

* Why didn't this work for Python 3.7? The abstract reason is because such compiler optimizations are implementation specific (i.e. may change with version, OS, etc). I'm still figuring out what exact implementation change cause the issue, you can check out this [issue](https://github.com/satwikkansal/wtfpython/issues/100) for updates.

---


### ‚ñ∂ Hash brownies
<!-- Example ID: eb17db53-49fd-4b61-85d6-345c5ca213ff --->
1\.
```py
some_dict = {}
some_dict[5.5] = "JavaScript"
some_dict[5.0] = "Ruby"
some_dict[5] = "Python"
```

**K·∫øt qu·∫£:**

```py
>>> some_dict[5.5]
"JavaScript"
>>> some_dict[5.0] # "Python" chi·∫øm l·∫•y kho√° (key) c·ªßa "Ruby"?
"Python"
>>> some_dict[5] 
"Python"

>>> complex_five = 5 + 0j
>>> type(complex_five)
complex
>>> some_dict[complex_five]
"Python"
```

Th·∫ø qu√°i n√†o m√† to√†n in ra Python?


#### üí° Gi·∫£i th√≠ch

* T√≠nh duy nh·∫•t c·ªßa c√°c kho√° (keys) trong c·∫•u tr√∫c d·ªØ li·ªáu t·ª´ ƒëi·ªÉn c·ªßa ƒë∆∞·ª£c x√°c ƒë·ªãnh b·ªüi  *s·ª± t∆∞∆°ng ƒë∆∞∆°ng*, ch·ª© kh√¥ng ph·∫£i d·ª±a tr√™n danh t√≠nh. Do ƒë√≥ d·∫´u cho `5`, `5.0`, v√† `5 + 0j` l√† c√°c ƒë·ªëi t∆∞·ª£ng ri√™ng bi·ªát c√≥ ki·ªÉu kh√°c nhau, nh∆∞ng b·ªüi v√¨ ch√∫ng bƒÉng nhau n√™n kh√¥ng th·ªÉ t·ªìn t·∫°i nh∆∞ m·ªôt kho√° ri√™ng c·ªßa `dict` (ho·∫∑c `set`). Khi b·∫°n th√™m c√°c kho√° n√†y v√†o t·ª´ ƒëi·ªÉn sau ƒë√≥ tra gi√° tr·ªã c·ªßa kho√° ƒë√≥ d·ª±a tr√™n gi·∫£ ƒë·ªãnh v·ªÅ s·ª± t∆∞∆°ng ƒë∆∞∆°ng th√¨ Python ch·ªâ tr·∫£ v·ªÅ gi√° tr·ªã c·ªßa kho√° ƒë∆∞·ª£c ch√®n v√†o ban ƒë·∫ßu (thay v√¨ tr·∫£ l·∫°i l·ªói v·ªÅ truy xu·∫•t kho√° `KeyError`):
  ```py
  >>> 5 == 5.0 == 5 + 0j
  True
  >>> 5 is not 5.0 is not 5 + 0j
  True
  >>> some_dict = {}
  >>> some_dict[5.0] = "Ruby"
  >>> 5.0 in some_dict
  True
  >>> (5 in some_dict) and (5 + 0j in some_dict)
  True
  ```
* Nguy√™n l√Ω tr√™n c≈©ng √°p d·ª•ng khi b·∫°n g√°n gi√° tr·ªã cho kho√°. Khi b·∫°n th·ª±c hi·ªán ph√©p g√°n `some_dict[5] = "Python"`, Python t√¨m ph·∫ßn t·ª≠ c√≥ s·∫µn trong t·ª´ ƒëi·ªÉn c√≥ kho√° t∆∞∆°ng ƒë∆∞∆°ng, trong tr∆∞·ªùng h·ª£p n√†y n√® `5.0 -> "Ruby"`, ghi ƒë√® l√™n gi√° tr·ªã c·ªßa kho√° n√†y ngay, v√† l·ªù ƒëi kho√° t∆∞∆°ng ƒë∆∞∆°ng m√† b·∫°n m·ªõi cung c·∫•p.
  ```py
  >>> some_dict
  {5.0: 'Ruby'}
  >>> some_dict[5] = "Python"
  >>> some_dict
  {5.0: 'Python'}
  ```

* V·∫≠y l√†m sao ƒë·ªÉ c·∫≠p nh·∫≠t kho√° `5` v√†o t·ª´ ƒëi·ªÉn (thay v√¨ `5.0`)? Th·ª±c s·ª± l√† ch√∫ng ta kh√¥ng th·ªÉ l√†m ƒëi·ªÅu ƒë√≥ v∆°i m·ªôt thao t√°c, nh∆∞ng ta c√≥ th·ªÉ xo√° ƒëi kho√° c≈©  (`del some_dict[5.0]`), v√† sau ƒë√≥ thi·∫øt l·∫≠p kho√° m·ªõi(`some_dict[5]`) ƒë·ªÉ c√≥ th·ªÉ l·∫•y ƒë∆∞·ª£c kho√° `5` thay v√¨ `5.0`, tuy nhi√™n c√°ch n√†y √≠t ai x√†i t·ªõi l·∫Øm.


* L√†m th·∫ø n√†o Python t√¨m kho√° `5` trong t·ª´ ƒëi·ªÉn c√≥ ch·ª©a s·∫µn kho√° `5.0`? N√≥ l√†m ƒë∆∞·ª£c ƒëi·ªÅu ƒë√≥ m√† kh√¥ng ph·∫£i d√≤ qua m·ªçi ph·∫ßn t·ª≠ trong t·ª´ ƒëi·ªÉn th√¥ng qua s·ª≠ d·ª•ng c√°c h√†m bƒÉm (hash functions), do ƒë√≥ t·ªën th·ªùi gian ch·∫°y h·∫±ng s·ªë (constant time). Khi Python tra  kho√° t√™n `foo` trong m·ªôt t∆∞ ƒëi·ªÉn, ƒë·∫ßu ti√™n n√≥ th·ª±c hi·ªán h√†m bƒÉm `hash(foo)` (v·ªõi th·ªùi gian ch·∫°y h·∫±ng s·ªë). B·ªüi v√¨ trong Python c√°c ƒë·ªëi t∆∞·ª£ng bƒÉng nhau khi ch√∫ng c√≥ chung m·ªôt gi√° tr·ªã bƒÉm ([ƒë·ªçc th√™m ·ªü ƒë√¢y](https://docs.python.org/3/reference/datamodel.html#object.__hash__) here), `5`, `5.0`, and `5 + 0j` have the same hash value.
  ```py
  >>> 5 == 5.0 == 5 + 0j
  True
  >>> hash(5) == hash(5.0) == hash(5 + 0j)
  True
  ```
  **Ghi ch√∫:** C√°c ƒë·ªëi t∆∞·ª£ng c√≥ gi√° tr·ªã bƒÉm bƒÉng nhau ch∆∞a ch·∫Øc ƒë√£ b·∫±ng nhau. (V·∫´n ƒë·ªÅ n√†y ƒë∆∞·ª£c bi·∫øt t·ªõi v·ªõi t√™n g·ªçi [hash collision](https://en.wikipedia.org/wiki/Collision_(computer_science)), v√† gi·∫£m ƒëi hi·ªáu nƒÉng v·ªõi th·ªùi gian h·∫±ng s·ªë qua vi·ªác d√πng h√†m bƒÉm.)

---

### ‚ñ∂ Deep down, we're all the same.
<!-- Example ID: 8f99a35f-1736-43e2-920d-3b78ec35da9b --->
```py
class WTF:
  pass
```

**Output:**
```py
>>> WTF() == WTF() # two different instances can't be equal
False
>>> WTF() is WTF() # identities are also different
False
>>> hash(WTF()) == hash(WTF()) # hashes _should_ be different as well
True
>>> id(WTF()) == id(WTF())
True
```

#### üí° Explanation:

* When `id` was called, Python created a `WTF` class object and passed it to the `id` function. The `id` function takes its `id` (its memory location), and throws away the object. The object is destroyed.
* When we do this twice in succession, Python allocates the same memory location to this second object as well. Since (in CPython) `id` uses the memory location as the object id, the id of the two objects is the same.
* So, the object's id is unique only for the lifetime of the object. After the object is destroyed, or before it is created, something else can have the same id.
* But why did the `is` operator evaluated to `False`? Let's see with this snippet.
  ```py
  class WTF(object):
    def __init__(self): print("I")
    def __del__(self): print("D")
  ```

  **Output:**
  ```py
  >>> WTF() is WTF()
  I
  I
  D
  D
  False
  >>> id(WTF()) == id(WTF())
  I
  D
  I
  D
  True
  ```
  As you may observe, the order in which the objects are destroyed is what made all the difference here.

---

### ‚ñ∂ Disorder within order *
<!-- Example ID: 91bff1f8-541d-455a-9de4-6cd8ff00ea66 --->
```py
from collections import OrderedDict

dictionary = dict()
dictionary[1] = 'a'; dictionary[2] = 'b';

ordered_dict = OrderedDict()
ordered_dict[1] = 'a'; ordered_dict[2] = 'b';

another_ordered_dict = OrderedDict()
another_ordered_dict[2] = 'b'; another_ordered_dict[1] = 'a';

class DictWithHash(dict):
    """
    A dict that also implements __hash__ magic.
    """
    __hash__ = lambda self: 0

class OrderedDictWithHash(OrderedDict):
    """
    An OrderedDict that also implements __hash__ magic.
    """
    __hash__ = lambda self: 0
```

**Output**
```py
>>> dictionary == ordered_dict # If a == b
True
>>> dictionary == another_ordered_dict # and b == c
True
>>> ordered_dict == another_ordered_dict # then why isn't c == a ??
False

# We all know that a set consists of only unique elements,
# let's try making a set of these dictionaries and see what happens...

>>> len({dictionary, ordered_dict, another_ordered_dict})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'dict'

# Makes sense since dict don't have __hash__ implemented, let's use
# our wrapper classes.
>>> dictionary = DictWithHash()
>>> dictionary[1] = 'a'; dictionary[2] = 'b';
>>> ordered_dict = OrderedDictWithHash()
>>> ordered_dict[1] = 'a'; ordered_dict[2] = 'b';
>>> another_ordered_dict = OrderedDictWithHash()
>>> another_ordered_dict[2] = 'b'; another_ordered_dict[1] = 'a';
>>> len({dictionary, ordered_dict, another_ordered_dict})
1
>>> len({ordered_dict, another_ordered_dict, dictionary}) # changing the order
2
```

What is going on here?

#### üí° Explanation:

- The reason why intransitive equality didn't hold among `dictionary`, `ordered_dict` and `another_ordered_dict` is because of the way `__eq__` method is implemented in `OrderedDict` class. From the [docs](https://docs.python.org/3/library/collections.html#ordereddict-objects)
  
    > Equality tests between OrderedDict objects are order-sensitive and are implemented as `list(od1.items())==list(od2.items())`. Equality tests between `OrderedDict` objects and other Mapping objects are order-insensitive like regular dictionaries.
- The reason for this equality in behavior is that it allows `OrderedDict` objects to be directly substituted anywhere a regular dictionary is used.
- Okay, so why did changing the order affect the length of the generated `set` object? The answer is the lack of intransitive equality only. Since sets are "unordered" collections of unique elements, the order in which elements are inserted shouldn't matter. But in this case, it does matter. Let's break it down a bit,
    ```py
    >>> some_set = set()
    >>> some_set.add(dictionary) # these are the mapping objects from the snippets above
    >>> ordered_dict in some_set
    True
    >>> some_set.add(ordered_dict)
    >>> len(some_set)
    1
    >>> another_ordered_dict in some_set
    True
    >>> some_set.add(another_ordered_dict)
    >>> len(some_set)
    1

    >>> another_set = set()
    >>> another_set.add(ordered_dict)
    >>> another_ordered_dict in another_set
    False
    >>> another_set.add(another_ordered_dict)
    >>> len(another_set)
    2
    >>> dictionary in another_set
    True
    >>> another_set.add(another_ordered_dict)
    >>> len(another_set)
    2
    ```
    So the inconsistency is due to `another_ordered_dict in another_set` being `False` because `ordered_dict` was already present in `another_set` and as observed before, `ordered_dict == another_ordered_dict` is `False`.

---

### ‚ñ∂ Keep trying... *
<!-- Example ID: b4349443-e89f-4d25-a109-82616be9d41a --->
```py
def some_func():
    try:
        return 'from_try'
    finally:
        return 'from_finally'

def another_func(): 
    for _ in range(3):
        try:
            continue
        finally:
            print("Finally!")

def one_more_func(): # A gotcha!
    try:
        for i in range(3):
            try:
                1 / i
            except ZeroDivisionError:
                # Let's throw it here and handle it outside for loop
                raise ZeroDivisionError("A trivial divide by zero error")
            finally:
                print("Iteration", i)
                break
    except ZeroDivisionError as e:
        print("Zero division error occurred", e)
```

**Output:**

```py
>>> some_func()
'from_finally'

>>> another_func()
Finally!
Finally!
Finally!

>>> 1 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero

>>> one_more_func()
Iteration 0

```

#### üí° Explanation:

- When a `return`, `break` or `continue` statement is executed in the `try` suite of a "try‚Ä¶finally" statement, the `finally` clause is also executed on the way out.
- The return value of a function is determined by the last `return` statement executed. Since the `finally` clause always executes, a `return` statement executed in the `finally` clause will always be the last one executed.
- The caveat here is, if the finally clause executes a `return` or `break` statement, the temporarily saved exception is discarded.

---


### ‚ñ∂ For what?
<!-- Example ID: 64a9dccf-5083-4bc9-98aa-8aeecde4f210 --->
```py
some_string = "wtf"
some_dict = {}
for i, some_dict[i] in enumerate(some_string):
    i = 10
```

**Output:**
```py
>>> some_dict # An indexed dict appears.
{0: 'w', 1: 't', 2: 'f'}
```

####  üí° Explanation:

* A `for` statement is defined in the [Python grammar](https://docs.python.org/3/reference/grammar.html) as:
  ```
  for_stmt: 'for' exprlist 'in' testlist ':' suite ['else' ':' suite]
  ```
  Where `exprlist` is the assignment target. This means that the equivalent of `{exprlist} = {next_value}` is **executed for each item** in the iterable.
  An interesting example that illustrates this:
  ```py
  for i in range(4):
      print(i)
      i = 10
  ```

  **Output:**
  ```
  0
  1
  2
  3
  ```

  Did you expect the loop to run just once?

  **üí° Explanation:**

  - The assignment statement `i = 10` never affects the iterations of the loop because of the way for loops work in Python. Before the beginning of every iteration, the next item provided by the iterator (`range(4)` in this case) is unpacked and assigned the target list variables (`i` in this case).

* The `enumerate(some_string)` function yields a new value `i` (a counter going up) and a character from the `some_string` in each iteration. It then sets the (just assigned) `i` key of the dictionary `some_dict` to that character. The unrolling of the loop can be simplified as:
  ```py
  >>> i, some_dict[i] = (0, 'w')
  >>> i, some_dict[i] = (1, 't')
  >>> i, some_dict[i] = (2, 'f')
  >>> some_dict
  ```

---

### ‚ñ∂ Evaluation time discrepancy
<!-- Example ID: 6aa11a4b-4cf1-467a-b43a-810731517e98 --->
1\.
```py
array = [1, 8, 15]
# A typical generator expression
gen = (x for x in array if array.count(x) > 0)
array = [2, 8, 22]
```

**Output:**

```py
>>> print(list(gen)) # Where did the other values go?
[8]
```

2\.

```py
array_1 = [1,2,3,4]
gen_1 = (x for x in array_1)
array_1 = [1,2,3,4,5]

array_2 = [1,2,3,4]
gen_2 = (x for x in array_2)
array_2[:] = [1,2,3,4,5]
```

**Output:**
```py
>>> print(list(gen_1))
[1, 2, 3, 4]

>>> print(list(gen_2))
[1, 2, 3, 4, 5]
```

3\.

```py
array_3 = [1, 2, 3]
array_4 = [10, 20, 30]
gen = (i + j for i in array_3 for j in array_4)

array_3 = [4, 5, 6]
array_4 = [400, 500, 600]
```

**Output:**
```py
>>> print(list(gen))
[401, 501, 601, 402, 502, 602, 403, 503, 603]
```

#### üí° Explanation

- In a [generator](https://wiki.python.org/moin/Generators) expression, the `in` clause is evaluated at declaration time, but the conditional clause is evaluated at runtime.
- So before runtime, `array` is re-assigned to the list `[2, 8, 22]`, and since out of `1`, `8` and `15`, only the count of `8` is greater than `0`, the generator only yields `8`.
- The differences in the output of `g1` and `g2` in the second part is due the way variables `array_1` and `array_2` are re-assigned values.
- In the first case, `array_1` is binded to the new object `[1,2,3,4,5]` and since the `in` clause is evaluated at the declaration time it still refers to the old object `[1,2,3,4]` (which is not destroyed).
- In the second case, the slice assignment to `array_2` updates the same old object `[1,2,3,4]` to `[1,2,3,4,5]`. Hence both the `g2` and `array_2` still have reference to the same object (which has now been updated to `[1,2,3,4,5]`).
- Okay, going by the logic discussed so far, shouldn't be the value of `list(g)` in the third snippet be `[11, 21, 31, 12, 22, 32, 13, 23, 33]`? (because `array_3` and `array_4` are going to behave just like `array_1`). The reason why (only) `array_4` values got updated is explained in [PEP-289](https://www.python.org/dev/peps/pep-0289/#the-details)
  
    > Only the outermost for-expression is evaluated immediately, the other expressions are deferred until the generator is run.

---


### ‚ñ∂ `is not ...` kh√¥ng ph·∫£i l√† `is (not ...)`

<!-- Example ID: b26fb1ed-0c7d-4b9c-8c6d-94a58a055c0d --->
```py
>>> 'something' is not None
True
>>> 'something' is (not None)
False
```

#### üí° Gi·∫£i th√≠ch

- `is not` l√† m·ªôt to√°n t·ª≠ nh·ªã ph√¢n ƒë∆°n, v√† khi th·ª±c hi·ªán s·∫Ω cho k·∫øt qu·∫£ kh√°c v·ªõi s·ª≠ d·ª•ng `is` v√† `not` ri√™ng bi·ªát.
- `is not` cho ra k·∫øt qu·∫£ `False` khi c√°c bi·∫øn ·ªü hai ƒë·∫ßu c·ªßa n√≥ tr·ªè v·ªÅ c√πng m·ªôt ƒë·ªëi t∆∞·ª£ng , v√† n·∫øu hai bi·∫øn n√†y tr·ªè v·ªÅ kh√°c ƒë·ªëi t∆∞·ª£ng, k·∫øt qu·∫£ s·∫Ω l√† `True`. C·ª• th·ªÉ, `None` v√† `something` tr·ªè v·ªÅ hai bi·∫øn kh√°c nhau n√™n k·∫øt qu·∫£ l√† `True`
- Trong v√≠ d·ª• tr√™n, `(not None)` s·∫Ω cho ra k·∫øt qu·∫£ `True` b·ªüi v√¨ khi s·ª≠ d·ª•ng trong ph√©p so s√°nh lu·∫≠n l√Ω `None` t∆∞∆°ng ƒë∆∞∆°ng v·ªõi `False`, do ƒë√≥ d√≤ng m√£ tr√™n s·∫Ω tr·ªü th√†nh `'something' is True`. C·ª• th·ªÉ, do `something` v√† `True` tr·ªè v·ªÅ hai ƒë·ªëi t∆∞·ª£ng kh√°c nhau n√™n k·∫øt qu·∫£ l√† `False`

---

### ‚ñ∂ A tic-tac-toe where X wins in the first attempt!
<!-- Example ID: 69329249-bdcb-424f-bd09-cca2e6705a7a --->

```py
# Let's initialize a row
row = [""] * 3 #row i['', '', '']
# Let's make a board
board = [row] * 3
```

**Output:**

```py
>>> board
[['', '', ''], ['', '', ''], ['', '', '']]
>>> board[0]
['', '', '']
>>> board[0][0]
''
>>> board[0][0] = "X"
>>> board
[['X', '', ''], ['X', '', ''], ['X', '', '']]
```

We didn't assign three `"X"`s, did we?

#### üí° Explanation:

When we initialize `row` variable, this visualization explains what happens in the memory

![image](/images/tic-tac-toe/after_row_initialized.png)

And when the `board` is initialized by multiplying the `row`, this is what happens inside the memory (each of the elements `board[0]`, `board[1]` and `board[2]` is a reference to the same list referred by `row`)

![image](/images/tic-tac-toe/after_board_initialized.png)

We can avoid this scenario here by not using `row` variable to generate `board`. (Asked in [this](https://github.com/satwikkansal/wtfpython/issues/68) issue).

```py
>>> board = [['']*3 for _ in range(3)]
>>> board[0][0] = "X"
>>> board
[['X', '', ''], ['', '', ''], ['', '', '']]
```

---

### ‚ñ∂ The sticky output function
<!-- Example ID: 4dc42f77-94cb-4eb5-a120-8203d3ed7604 --->

1\.

```py
funcs = []
results = []
for x in range(7):
    def some_func():
        return x
    funcs.append(some_func)
    results.append(some_func())  # note the function call here

funcs_results = [func() for func in funcs]
```

**Output:**

```py
>>> results
[0, 1, 2, 3, 4, 5, 6]
>>> funcs_results
[6, 6, 6, 6, 6, 6, 6]
```
Even when the values of `x` were different in every iteration prior to appending `some_func` to `funcs`, all the functions return 6.

2\.

```py
>>> powers_of_x = [lambda x: x**i for i in range(10)]
>>> [f(2) for f in powers_of_x]
[512, 512, 512, 512, 512, 512, 512, 512, 512, 512]
```

#### üí° Explanation

- When defining a function inside a loop that uses the loop variable in its body, the loop function's closure is bound to the variable, not its value. So all of the functions use the latest value assigned to the variable for computation.

- To get the desired behavior you can pass in the loop variable as a named variable to the function. **Why does this work?** Because this will define the variable again within the function's scope.

    ```py
    funcs = []
    for x in range(7):
        def some_func(x=x):
            return x
        funcs.append(some_func)
    ```

    **Output:**
    ```py
    >>> funcs_results = [func() for func in funcs]
    >>> funcs_results
    [0, 1, 2, 3, 4, 5, 6]
    ```

---

### ‚ñ∂ B√†i to√°n con g√† v√† qu·∫£ tr·ª©ng *
<!-- Example ID: 60730dc2-0d79-4416-8568-2a63323b3ce8 --->
1\.
```py
>>> isinstance(3, int)
True
>>> isinstance(type, object)
True
>>> isinstance(object, type)
True
```

ƒê√¢u l√† l·ªõp c∆° b·∫£n cu·ªëi c√πng ? C√≤n nhi·ªÅu th·ª© g√¢y kh√≥ hi·ªÉu h∆°n n·ªØa sau ƒë√¢y

2\. 

```py
>>> class A: pass
>>> isinstance(A, A)
False
>>> isinstance(type, type)
True
>>> isinstance(object, object)
True
```

3\.

```py
>>> issubclass(int, object)
True
>>> issubclass(type, object)
True
>>> issubclass(object, type)
False
```


#### üí° Gi·∫£i th√≠ch

- `type` l√† m·ªôt [metaclass](https://realpython.com/python-metaclasses/) trong Python.
- **M·ªçi th·ª©** ƒë·ªÅu l√† m·ªôt ƒë·ªëi t∆∞·ª£ng `object` trong Python, bao g·ªìm c·∫£ c√°c l·ªõp (classes) c≈©ng nh∆∞ l√† c√°c hi·ªán th·ª±c c·ªßa ch√∫ng (instances).
- L·ªõp `type` l√† metaclass c·ªßa l·ªõp `object`, do ƒë√≥ m·ªçi l·ªõp (g·ªìm c·∫£ `type`) th·ª´a h∆∞·ªüng tr·ª±c ti·∫øp hay gi√°n ti·∫øp t·ª´ `object`.
- Kh√¥ng c√≥ m·ªôt l·ªõp n√†o n·∫±m gi·ªØa l·ªõp `object` v√† `type`. V·∫•n ƒë·ªÅ ƒë·ªëi v·ªõi c√°c ƒëo·∫°n m√£ ph√≠a tr√™n n·∫±m ·ªü c√°ch ta t√¨m c√°c m·ªëi quan h·ªá gi·ªØa c√°c l·ªõp trong Python (d√πng `issubclass` v√† `isinstance`). M·ªói quan h·ªá gi·ªØa `object` v√† `type` kh√¥ng th·ªÉ ƒë∆∞·ª£c ƒë·ªãnh nghƒ©a trong Python ƒë∆°n thu·∫ßn. Ch√≠nh x√°c h∆°n, nghƒ©a l√†,
    + L·ªõp A l√† m·ªôt hi·ªán th·ª±c c·ªßa l·ªõp B, v√† l·ªõp B l√† m·ªôt hi·ªán th·ª±c c·ªßa l·ªõp A.  
    + L·ªõp A l√† m·ªôt hi·ªán th·ª±c c·ªßa ch√≠nh n√≥.
- These relationships between `object` and `type` (both being instances of each other as well as themselves) exist in Python because of "cheating" at the implementation level.
- C√°c m·ªëi quan h·ªá gi·ªØa `object` v√† `type` (·ªü c·∫£ hai c·∫•p ƒë·ªô hi·ªán th·ª±c c≈©ng nh∆∞ ch√≠nh l·ªõp ƒë√≥) t·ªìn t·∫°i l√† do vi·ªác "ƒÉn gian" khi tri·ªÉn khai c√°c l·ªõp n√†y.
---

### ‚ñ∂ Subclass relationships
<!-- Example ID: 9f6d8cf0-e1b5-42d0-84a0-4cfab25a0bc0 --->
**Output:**
```py
>>> from collections import Hashable
>>> issubclass(list, object)
True
>>> issubclass(object, Hashable)
True
>>> issubclass(list, Hashable)
False
```

The Subclass relationships were expected to be transitive, right? (i.e., if `A` is a subclass of `B`, and `B` is a subclass of `C`, the `A` _should_ a subclass of `C`)

#### üí° Explanation:

* Subclass relationships are not necessarily transitive in Python. Anyone is allowed to define their own, arbitrary `__subclasscheck__` in a metaclass.
* When `issubclass(cls, Hashable)` is called, it simply looks for non-Falsey "`__hash__`" method in `cls` or anything it inherits from.
* Since `object` is hashable, but `list` is non-hashable, it breaks the transitivity relation.
* More detailed explanation can be found [here](https://www.naftaliharris.com/blog/python-subclass-intransitivity/).

---

### ‚ñ∂ All-true-ation *

<!-- Example ID: dfe6d845-e452-48fe-a2da-0ed3869a8042 -->

```py
>>> all([True, True, True])
True
>>> all([True, True, False])
False

>>> all([])
True
>>> all([[]])
False
>>> all([[[]]])
True
```

Why's this True-False alteration?

#### üí° Explanation:

- The implementation of `all` function is equivalent to

- ```py
  def all(iterable):
      for element in iterable:
          if not element:
              return False
      return True
  ```

- `all([])` returns `True` since the iterable is empty. 
- `all([[]])` returns `False` because `not []` is `True` is equivalent to `not False` as the list inside the iterable is empty.
- `all([[[]]])` and higher recursive variants are always `True` since `not [[]]`, `not [[[]]]`, and so on are equivalent to `not True`.

---

### ‚ñ∂ The surprising comma
<!-- Example ID: 31a819c8-ed73-4dcc-84eb-91bedbb51e58 --->
**Output (< 3.6):**

```py
>>> def f(x, y,):
...     print(x, y)
...
>>> def g(x=4, y=5,):
...     print(x, y)
...
>>> def h(x, **kwargs,):
  File "<stdin>", line 1
    def h(x, **kwargs,):
                     ^
SyntaxError: invalid syntax

>>> def h(*args,):
  File "<stdin>", line 1
    def h(*args,):
                ^
SyntaxError: invalid syntax
```

#### üí° Explanation:

- Trailing comma is not always legal in formal parameters list of a Python function.
-  In Python, the argument list is defined partially with leading commas and partially with trailing commas. This conflict causes situations where a comma is trapped in the middle, and no rule accepts it.
-  **Note:** The trailing comma problem is [fixed in Python 3.6](https://bugs.python.org/issue9232). The remarks in [this](https://bugs.python.org/issue9232#msg248399) post discuss in brief different usages of trailing commas in Python.

---

### ‚ñ∂ Strings and the backslashes
<!-- Example ID: 6ae622c3-6d99-4041-9b33-507bd1a4407b --->
**Output:**
```py
>>> print("\"")
"

>>> print(r"\"")
\"

>>> print(r"\")
File "<stdin>", line 1
    print(r"\")
              ^
SyntaxError: EOL while scanning string literal

>>> r'\'' == "\\'"
True
```

#### üí° Explanation

- In a usual python string, the backslash is used to escape characters that may have a special meaning (like single-quote, double-quote, and the backslash itself).
    ```py
    >>> "wt\"f"
    'wt"f'
    ```
- In a raw string literal (as indicated by the prefix `r`),  the backslashes pass themselves as is along with the behavior of escaping the following character.
    ```py
    >>> r'wt\"f' == 'wt\\"f'
    True
    >>> print(repr(r'wt\"f')
    'wt\\"f'

    >>> print("\n")

    >>> print(r"\\n")
    '\\\\n'
    ```
- This means when a parser encounters a backslash in a raw string, it expects another character following it. And in our case (`print(r"\")`), the backslash escaped the trailing quote, leaving the parser without a terminating quote (hence the `SyntaxError`). That's why backslashes don't work at the end of a raw string.

---

### ‚ñ∂ not knot!
<!-- Example ID: 7034deb1-7443-417d-94ee-29a800524de8 --->
```py
x = True
y = False
```

**Output:**
```py
>>> not x == y
True
>>> x == not y
  File "<input>", line 1
    x == not y
           ^
SyntaxError: invalid syntax
```

#### üí° Explanation:

* Operator precedence affects how an expression is evaluated, and `==` operator has higher precedence than `not` operator in Python.
* So `not x == y` is equivalent to `not (x == y)` which is equivalent to `not (True == False)` finally evaluating to `True`.
* But `x == not y` raises a `SyntaxError` because it can be thought of being equivalent to `(x == not) y` and not `x == (not y)` which you might have expected at first sight.
* The parser expected the `not` token to be a part of the `not in` operator (because both `==` and `not in` operators have the same precedence), but after not being able to find an `in` token following the `not` token, it raises a `SyntaxError`.

---

### ‚ñ∂ Half triple-quoted strings
<!-- Example ID: c55da3e2-1034-43b9-abeb-a7a970a2ad9e --->
**Output:**
```py
>>> print('wtfpython''')
wtfpython
>>> print("wtfpython""")
wtfpython
>>> # The following statements raise `SyntaxError`
>>> # print('''wtfpython')
>>> # print("""wtfpython")
  File "<input>", line 3
    print("""wtfpython")
                        ^
SyntaxError: EOF while scanning triple-quoted string literal
```

#### üí° Explanation:
+ Python supports implicit [string literal concatenation](https://docs.python.org/2/reference/lexical_analysis.html#string-literal-concatenation), Example,
  ```
  >>> print("wtf" "python")
  wtfpython
  >>> print("wtf" "") # or "wtf"""
  wtf
  ```
+ `'''` and `"""` are also string delimiters in Python which causes a SyntaxError because the Python interpreter was expecting a terminating triple quote as delimiter while scanning the currently encountered triple quoted string literal.

---

### ‚ñ∂ What's wrong with booleans?
<!-- Example ID: 0bba5fa7-9e6d-4cd2-8b94-952d061af5dd --->
1\.

```py
# A simple example to count the number of booleans and
# integers in an iterable of mixed data types.
mixed_list = [False, 1.0, "some_string", 3, True, [], False]
integers_found_so_far = 0
booleans_found_so_far = 0

for item in mixed_list:
    if isinstance(item, int):
        integers_found_so_far += 1
    elif isinstance(item, bool):
        booleans_found_so_far += 1
```

**Output:**
```py
>>> integers_found_so_far
4
>>> booleans_found_so_far
0
```


2\.
```py
>>> some_bool = True
>>> "wtf" * some_bool
'wtf'
>>> some_bool = False
>>> "wtf" * some_bool
''
```

3\.

```py
def tell_truth():
    True = False
    if True == False:
        print("I have lost faith in truth!")
```

**Output (< 3.x):**

```py
>>> tell_truth()
I have lost faith in truth!
```



#### üí° Explanation:

* `bool` is a subclass of `int` in Python
    
    ```py
    >>> issubclass(bool, int)
    True
    >>> issubclass(int, bool)
    False
    ```
    
* And thus, `True` and `False` are instances of `int`
  ```py
  >>> isinstance(True, int)
  True
  >>> isinstance(False, int)
  True
  ```

* The integer value of `True` is `1` and that of `False` is `0`.
  ```py
  >>> int(True)
  1
  >>> int(False)
  0
  ```

* See this StackOverflow [answer](https://stackoverflow.com/a/8169049/4354153) for the rationale behind it.

* Initially, Python used to have no `bool` type (people used 0 for false and non-zero value like 1 for true).  `True`, `False`, and a `bool` type was added in 2.x versions, but, for backward compatibility, `True` and `False` couldn't be made constants. They just were built-in variables, and it was possible to reassign them

* Python 3 was backward-incompatible, the issue was finally fixed, and thus the last snippet won't work with Python 3.x!

---

### ‚ñ∂ Class attributes and instance attributes
<!-- Example ID: 6f332208-33bd-482d-8106-42863b739ed9 --->
1\.
```py
class A:
    x = 1

class B(A):
    pass

class C(A):
    pass
```

**Output:**
```py
>>> A.x, B.x, C.x
(1, 1, 1)
>>> B.x = 2
>>> A.x, B.x, C.x
(1, 2, 1)
>>> A.x = 3
>>> A.x, B.x, C.x # C.x changed, but B.x didn't
(3, 2, 3)
>>> a = A()
>>> a.x, A.x
(3, 3)
>>> a.x += 1
>>> a.x, A.x
(4, 3)
```

2\.
```py
class SomeClass:
    some_var = 15
    some_list = [5]
    another_list = [5]
    def __init__(self, x):
        self.some_var = x + 1
        self.some_list = self.some_list + [x]
        self.another_list += [x]
```

**Output:**

```py
>>> some_obj = SomeClass(420)
>>> some_obj.some_list
[5, 420]
>>> some_obj.another_list
[5, 420]
>>> another_obj = SomeClass(111)
>>> another_obj.some_list
[5, 111]
>>> another_obj.another_list
[5, 420, 111]
>>> another_obj.another_list is SomeClass.another_list
True
>>> another_obj.another_list is some_obj.another_list
True
```

#### üí° Explanation:

* Class variables and variables in class instances are internally handled as dictionaries of a class object. If a variable name is not found in the dictionary of the current class, the parent classes are searched for it.
* The `+=` operator modifies the mutable object in-place without creating a new object. So changing the attribute of one instance affects the other instances and the class attribute as well.

---

### ‚ñ∂ Non-reflexive class method *

<!-- Example ID: 3649771a-f733-413c-8060-3f9f167b83fd -->

```py
class SomeClass:
        def instance_method(self):
                pass
        
        @classmethod
        def class_method(cls):
                pass
```

**Output:**

```py
>>> SomeClass.instance_method is SomeClass.instance_method
True
>>> SomeClass.class_method is SomeClass.class_method
False
>>> id(SomeClass.class_method) == id(SomeClass.class_method)
True
```

#### üí° Explanation:

- The reason `SomeClass.class_method is SomeClass.class_method` is `False` is due to the `@classmethod` decorator. 

  ```py
  >>> SomeClass.instance_method
  <function __main__.SomeClass.instance_method(self)>
  >>> SomeClass.class_method
  <bound method SomeClass.class_method of <class '__main__.SomeClass'>
  ```

  A new bound method every time `SomeClass.class_method` is accessed.

-  `id(SomeClass.class_method) == id(SomeClass.class_method)` returned `True` because the second allocation of memory for `class_method` happened at the same location of first deallocation (See Deep Down, we're all the same example for more detailed explanation). 

---


### ‚ñ∂ yielding None
<!-- Example ID: 5a40c241-2c30-40d0-8ba9-cf7e097b3b53 --->
```py
some_iterable = ('a', 'b')

def some_func(val):
    return "something"
```

**Output (<= 3.7.x):**

```py
>>> [x for x in some_iterable]
['a', 'b']
>>> [(yield x) for x in some_iterable]
<generator object <listcomp> at 0x7f70b0a4ad58>
>>> list([(yield x) for x in some_iterable])
['a', 'b']
>>> list((yield x) for x in some_iterable)
['a', None, 'b', None]
>>> list(some_func((yield x)) for x in some_iterable)
['a', 'something', 'b', 'something']
```

#### üí° Explanation:
- This is a bug in CPython's handling of `yield` in generators and comprehensions.
- Source and explanation can be found here: https://stackoverflow.com/questions/32139885/yield-in-list-comprehensions-and-generator-expressions
- Related bug report: http://bugs.python.org/issue10544
- Python 3.8+ no longer allows `yield` inside list comprehension and will throw a `SyntaxError`.

---


### ‚ñ∂ Yielding from... return! *
<!-- Example ID: 5626d8ef-8802-49c2-adbc-7cda5c550816 --->
1\.

```py
def some_func(x):
    if x == 3:
        return ["wtf"]
    else:
        yield from range(x)
```

**Output (> 3.3):**

```py
>>> list(some_func(3))
[]
```

Where did the `"wtf"` go? Is it due to some special effect of `yield from`? Let's validate that,

2\.

```py
def some_func(x):
    if x == 3:
        return ["wtf"]
    else:
        for i in range(x):
          yield i
```

**Output:**

```py
>>> list(some_func(3))
[]
```

The same result, this didn't work either.

#### üí° Explanation:

+ From Python 3.3 onwards, it became possible to use `return` statement with values inside generators (See [PEP380](https://www.python.org/dev/peps/pep-0380/)). The [official docs](https://www.python.org/dev/peps/pep-0380/#enhancements-to-stopiteration) say that,

> "... `return expr` in a generator causes `StopIteration(expr)` to be raised upon exit from the generator."

+ In the case of `some_func(3)`, `StopIteration` is raised at the beginning because of `return` statement. The `StopIteration` exception is automatically caught inside the `list(...)` wrapper and the `for` loop. Therefore, the above two snippets result in an empty list.

+ To get `["wtf"]` from the generator `some_func` we need to catch the `StopIteration` exception,

  ```py
  try:
      next(some_func(3))
  except StopIteration as e:
      some_string = e.value
  ```

  ```py
  >>> some_string
  ["wtf"]
  ```

---

### ‚ñ∂ Nan-reflexivity *
### ‚ñ∂ T√≠nh ph·∫£n x·∫° c·ªßa Nan *
<!-- Example ID: 59bee91a-36e0-47a4-8c7d-aa89bf1d3976 --->

1\.

```py
a = float('inf')
b = float('nan')
c = float('-iNf')  # C√°c strings n√†y kh√¥ng ph√¢n bi·ªát hoa hay th∆∞·ªùng
d = float('nan')
```

**K·∫øt qu·∫£:**

```py
>>> a
inf
>>> b
nan
>>> c
-inf
>>> float('some_other_string')
ValueError: could not convert string to float: some_other_string (L·ªói gi√° tr·ªã: Kh√¥ng th·ªÉ chuy·ªÉn ƒë·ªïi t·ª´ string sang float)
>>> a == -c # inf==inf
True
>>> None == None # None == None
True
>>> b == d # nh∆∞ng nan!=nan
False
>>> 50 / a
0.0
>>> a / a
nan
>>> 23 + b
nan
```

2\.

```py
>>> x = float('nan')
>>> y = x / x
>>> y is y # ƒë·ªãnh danh gi·ªëng nhau (c√πng tr·ªè v·ªÅ m·ªôt ƒë·ªëi t∆∞·ª£ng)
True
>>> y == y # G√≠a tr·ªã l·∫°i kh√¥ng b·∫±ng nhau
False
>>> [y] == [y] # Gi√° tr·ªã b·∫±ng nhau khi n·∫±m ·ªü trong m·ªôt list
True
```



#### üí° Gi·∫£i th√≠ch:

- `'inf'` v√† `'nan'` l√† c√°c strings ƒë·∫∑c bi·ªát (kh√¥ng ph√¢n bi·ªát hoa th∆∞·ªùng), khi ƒë∆∞·ª£c chuy·ªÉn ƒë·ªïi sang ki·ªÉu `float` s·∫Ω t∆∞∆°ng ·ª©ng bi·ªÉu di·ªÖn cho gi√° tr·ªã v√¥ h·∫°n "infinity" hay kh√¥ng ph·∫£i l√† m·ªôt s·ªë "not a number".

- Theo chu·∫©n c·ªßa IEEE th√¨ ` NaN != NaN`, tu√¢n theo quy t·∫Øc tr√™n s·∫Ω ph√° v·ª° gi·∫£ ƒë·ªãnh v·ªÅ t√≠nh t∆∞∆°ng ph·∫£n c·ªßa m·ªôt ph·∫ßn t·ª≠ trong m·ªôt t·∫≠p trong Python v√≠ d·ª•. n·∫øu `x` l√† m·ªôt ph·∫ßn t·ª≠ c·ªßa m·ªôt t·∫≠p `list`, c√°c ph√©p to√°n tr√™n c√°c ph·∫ßn t·ª≠ c·ªßa t·∫≠p nh∆∞ l√† so s√°nh s·∫Ω d·ª±a tr√™n gi·∫£i ƒë·ªãnh r·∫±ng `x == x`.  Do gi·∫£ ƒë·ªãnh n√†y n√™n ƒë·ªãnh danh ƒë∆∞·ª£c so s√°nh ƒë·∫ßu ti√™n (do nhanh h∆°n) khi so s√°nh hai ph·∫ßn t·ª≠, v√† c√°c gi√° tr·ªã ƒë∆∞·ª£c so s√°nh ch·ªâ khi c√°c ƒë·ªãnh danh kh√¥ng kh·ªõp. V√≠ d·ª• sau s·∫Ω gi√∫p b·∫°n d·ªÖ hi·ªÉu h∆°n
  ```py
  >>> x = float('nan')
  >>> x == x, [x] == [x]
  (False, True)
  >>> y = float('nan')
  >>> y == y, [y] == [y]
  (False, True)
  >>> x == y, [x] == [y]
  (False, False)
  ```

  Since the identities of `x` and `y` are different, the values are considered, which are also different; hence the comparison returns `False` this time.
  
 Do c√°c ƒë·ªãnh danh c·ªßa `x` v√† `y` kh√°c nhau, do ƒë√≥ gi√° tr·ªã c·ªßa ch√∫ng s·∫Ω ƒë∆∞·ª£c so s√°nh, m√† gi√° tr·ªã c·ªßa ch√∫ng kh√°c nhau trong v√≠ d·ª• n√†y; n√™n k·∫øt qu·∫£ tr·∫£ v·ªÅ l√† `False`. C·ª• th·ªÉ h∆°n, theo ti√™u chu·∫©n c·ªßa IEEE th√¨ `x` f va `y` ƒë·ªÉu c√≥ gi√° tr·ªã l√† `nan` khi ƒë∆∞·ª£c chuy·ªÉn ƒë·ªïi qua float, ` NaN != NaN` n√™n `x != y`, nh∆∞ng khi ƒë·∫∑t trong m·ªôt list th√¨ ƒë·ªãnh danh s·∫Ω ƒëc so s√°nh tr∆∞·ªõc n√™n `[x] == [y]`

- ƒê·ªçc th√™m: [Reflexivity, and other pillars of civilization](https://bertrandmeyer.com/2010/02/06/reflexivity-and-other-pillars-of-civilization/)

---

### ‚ñ∂ Mutating the immutable!

<!-- Example ID: 15a9e782-1695-43ea-817a-a9208f6bb33d --->

This might seem trivial if you know how references work in Python.
V√≠ d·ª• d∆∞·ªõi ƒë√¢y c√≥ v·∫ª t·∫ßm th∆∞·ªùng n·∫øu b·∫°n hi·ªÉu c√°ch c√°c tham chi·∫øu (references) ho·∫°t ƒë√¥ng trong Python.
```py
some_tuple = ("A", "tuple", "with", "values")
another_tuple = ([1, 2], [3, 4], [5, 6])
```

**Output:**
```py
>>> some_tuple[2] = "change this"
TypeError: 'tuple' object does not support item assignment (L·ªói v·ªÅ ki·ªÉu: ƒë·ªëi t∆∞·ª£ng 'tuple' kh√¥ng h·ªó tr·ª£ ph√©p g√°n ph·∫ßn t·ª≠)
>>> another_tuple[2].append(1000) # D√≤ng n√†y kh√¥ng b·ªã l·ªói
>>> another_tuple
([1, 2], [3, 4], [5, 6, 1000])
>>> another_tuple[2] += [99, 999]
TypeError: 'tuple' object does not support item assignment (L·ªói v·ªÅ ki·ªÉu: ƒë·ªëi t∆∞·ª£ng 'tuple' kh√¥ng h·ªó tr·ª£ ph√©p g√°n ph·∫ßn t·ª≠)
>>> another_tuple
([1, 2], [3, 4], [5, 6, 1000, 99, 999])
```

T√¥i ƒë√£ nghƒ© r·∫±ng c√°c tuples th√¨ b·∫•t bi·∫øn (immutable) ...
#### üí° Gi·∫£i th√≠ch:

* Tr√≠ch t·ª´ https://docs.python.org/2/reference/datamodel.html

    > C√°c chu·ªói b·∫•t bi·∫øn
        M·ªôt ƒë·ªëi t∆∞·ª£ng ki·ªÉu chu·ªói b·∫•t bi·∫øn kh√¥ng th·ªÉ thay ƒë·ªïi gi√° tr·ªã c·ªßa n√≥ sau khi ƒë∆∞·ª£c t·∫°o. (N·∫øu ƒë·ªëi t∆∞·ª£ng n√†y ch·ª©a c√°c tham chi·∫øu t·ªõi c√°c ƒë·ªëi t∆∞·ª£ng kh√°c, nh·ªØng ƒë·ªëi t∆∞·ª£ng c√≥ th·ªÉ thay ƒë·ªïi ƒë∆∞·ª£c; tuy th·∫ø, t·∫≠p h·ª£p c√°c ƒë·ªëi t∆∞·ª£ng ƒë∆∞·ª£c tr·ªè tr·ª±c ti·∫øp b·ªüi m·ªôt ƒë·ªëi t∆∞·ª£ng b·∫•t bi·∫øn kh√¥ng th·ªÉ thay ƒë·ªïi .)

* To√°n t·ª≠ `+=` thay ƒë·ªïi list t·∫°i ch·ªó. Ph√©p g√°n ph·∫ßn t·ª≠ kh√¥ng th·ª±c hi·ªán ƒë∆∞·ª£c, nh∆∞ng khi ngo·∫°i l·ªá x·∫£y ra, ph·∫ßn t·ª≠ ƒë√£ ƒë∆∞·ª£c thay ƒë·ªïi ngay t·∫°i ch·ªó.

---

### ‚ñ∂ The disappearing variable from outer scope
<!-- Example ID: 7f1e71b6-cb3e-44fb-aa47-87ef1b7decc8 --->

```py
e = 7
try:
    raise Exception()
except Exception as e:
    pass
```

**Output (Python 2.x):**
```py
>>> print(e)
# prints nothing
```

**Output (Python 3.x):**
```py
>>> print(e)
NameError: name 'e' is not defined
```

#### üí° Explanation:

* Source: https://docs.python.org/3/reference/compound_stmts.html#except

  When an exception has been assigned using `as` target, it is cleared at the end of the `except` clause. This is as if

  ```py
  except E as N:
      foo
  ```

  was translated into

  ```py
  except E as N:
      try:
          foo
      finally:
          del N
  ```

  This means the exception must be assigned to a different name to be able to refer to it after the except clause. Exceptions are cleared because, with the traceback attached to them, they form a reference cycle with the stack frame, keeping all locals in that frame alive until the next garbage collection occurs.

* The clauses are not scoped in Python. Everything in the example is present in the same scope, and the variable `e` got removed due to the execution of the `except` clause. The same is not the case with functions that have their separate inner-scopes. The example below illustrates this:

     ```py
     def f(x):
         del(x)
         print(x)

     x = 5
     y = [5, 4, 3]
     ```

     **Output:**
     ```py
     >>>f(x)
     UnboundLocalError: local variable 'x' referenced before assignment
     >>>f(y)
     UnboundLocalError: local variable 'x' referenced before assignment
     >>> x
     5
     >>> y
     [5, 4, 3]
     ```

* In Python 2.x, the variable name `e` gets assigned to `Exception()` instance, so when you try to print, it prints nothing.

    **Output (Python 2.x):**
    ```py
    >>> e
    Exception()
    >>> print e
    # Nothing is printed!
    ```

---


### ‚ñ∂ The mysterious key type conversion
<!-- Example ID: 00f42dd0-b9ef-408d-9e39-1bc209ce3f36 --->
```py
class SomeClass(str):
    pass

some_dict = {'s': 42}
```

**Output:**
```py
>>> type(list(some_dict.keys())[0])
str
>>> s = SomeClass('s')
>>> some_dict[s] = 40
>>> some_dict # expected: Two different keys-value pairs
{'s': 40}
>>> type(list(some_dict.keys())[0])
str
```

#### üí° Explanation:

* Both the object `s` and the string `"s"` hash to the same value because `SomeClass` inherits the `__hash__` method of `str` class.
* `SomeClass("s") == "s"` evaluates to `True` because `SomeClass` also inherits `__eq__` method from `str` class.
* Since both the objects hash to the same value and are equal, they are represented by the same key in the dictionary.
* For the desired behavior, we can redefine the `__eq__` method in `SomeClass`
  ```py
  class SomeClass(str):
    def __eq__(self, other):
        return (
            type(self) is SomeClass
            and type(other) is SomeClass
            and super().__eq__(other)
        )

    # When we define a custom __eq__, Python stops automatically inheriting the
    # __hash__ method, so we need to define it as well
    __hash__ = str.__hash__

  some_dict = {'s':42}
  ```

  **Output:**
  ```py
  >>> s = SomeClass('s')
  >>> some_dict[s] = 40
  >>> some_dict
  {'s': 40, 's': 42}
  >>> keys = list(some_dict.keys())
  >>> type(keys[0]), type(keys[1])
  (__main__.SomeClass, str)
  ```

---

### ‚ñ∂ Let's see if you can guess this?
<!-- Example ID: 81aa9fbe-bd63-4283-b56d-6fdd14c9105e --->
```py
a, b = a[b] = {}, 5
```

**Output:**
```py
>>> a
{5: ({...}, 5)}
```

#### üí° Explanation:

* According to [Python language reference](https://docs.python.org/2/reference/simple_stmts.html#assignment-statements), assignment statements have the form
  ```
  (target_list "=")+ (expression_list | yield_expression)
  ```
  and
  
> An assignment statement evaluates the expression list (remember that this can be a single expression or a comma-separated list, the latter yielding a tuple) and assigns the single resulting object to each of the target lists, from left to right.

* The `+` in `(target_list "=")+` means there can be **one or more** target lists. In this case, target lists are `a, b` and `a[b]` (note the expression list is exactly one, which in our case is `{}, 5`).

* After the expression list is evaluated, its value is unpacked to the target lists from **left to right**. So, in our case, first the `{}, 5` tuple is unpacked to `a, b` and we now have `a = {}` and `b = 5`.

* `a` is now assigned to `{}`, which is a mutable object.

* The second target list is `a[b]` (you may expect this to throw an error because both `a` and `b` have not been defined in the statements before. But remember, we just assigned `a` to `{}` and `b` to `5`).

* Now, we are setting the key `5` in the dictionary to the tuple `({}, 5)` creating a circular reference (the `{...}` in the output refers to the same object that `a` is already referencing). Another simpler example of circular reference could be
  ```py
  >>> some_list = some_list[0] = [0]
  >>> some_list
  [[...]]
  >>> some_list[0]
  [[...]]
  >>> some_list is some_list[0]
  True
  >>> some_list[0][0][0][0][0][0] == some_list
  True
  ```
  Similar is the case in our example (`a[b][0]` is the same object as `a`)

* So to sum it up, you can break the example down to
  ```py
  a, b = {}, 5
  a[b] = a, b
  ```
  And the circular reference can be justified by the fact that `a[b][0]` is the same object as `a`
  ```py
  >>> a[b][0] is a
  True
  ```

---
---

## Section: Slippery Slopes

### ‚ñ∂ Modifying a dictionary while iterating over it
<!-- Example ID: b4e5cdfb-c3a8-4112-bd38-e2356d801c41 --->
```py
x = {0: None}

for i in x:
    del x[i]
    x[i+1] = None
    print(i)
```

**Output (Python 2.7- Python 3.5):**

```
0
1
2
3
4
5
6
7
```

Yes, it runs for exactly **eight** times and stops.

#### üí° Explanation:

* Iteration over a dictionary that you edit at the same time is not supported.
* It runs eight times because that's the point at which the dictionary resizes to hold more keys (we have eight deletion entries, so a resize is needed). This is actually an implementation detail.
* How deleted keys are handled and when the resize occurs might be different for different Python implementations.
* So for Python versions other than Python 2.7 - Python 3.5, the count might be different from 8 (but whatever the count is, it's going to be the same every time you run it). You can find some discussion around this [here](https://github.com/satwikkansal/wtfpython/issues/53) or in [this](https://stackoverflow.com/questions/44763802/bug-in-python-dict) StackOverflow thread.
* Python 3.7.6 onwards, you'll see `RuntimeError: dictionary keys changed during iteration` exception if you try to do this.

---

### ‚ñ∂ Stubborn `del` operation
<!-- Example ID: 777ed4fd-3a2d-466f-95e7-c4058e61d78e --->
<!-- read-only -->

```py
class SomeClass:
    def __del__(self):
        print("Deleted!")
```

**Output:**
1\.
```py
>>> x = SomeClass()
>>> y = x
>>> del x # this should print "Deleted!"
>>> del y
Deleted!
```

Phew, deleted at last. You might have guessed what saved `__del__` from being called in our first attempt to delete `x`. Let's add more twists to the example.

2\.
```py
>>> x = SomeClass()
>>> y = x
>>> del x
>>> y # check if y exists
<__main__.SomeClass instance at 0x7f98a1a67fc8>
>>> del y # Like previously, this should print "Deleted!"
>>> globals() # oh, it didn't. Let's check all our global variables and confirm
Deleted!
{'__builtins__': <module '__builtin__' (built-in)>, 'SomeClass': <class __main__.SomeClass at 0x7f98a1a5f668>, '__package__': None, '__name__': '__main__', '__doc__': None}
```

Okay, now it's deleted :confused:

#### üí° Explanation:
+ `del x` doesn‚Äôt directly call `x.__del__()`.
+ When `del x` is encountered, Python deletes the name `x` from current scope and decrements by 1 the reference count of the object `x` referenced. `__del__()` is called only when the object's reference count reaches zero.
+ In the second output snippet, `__del__()` was not called because the previous statement (`>>> y`) in the interactive interpreter created another reference to the same object (specifically, the `_` magic variable which references the result value of the last non `None` expression on the REPL), thus preventing the reference count from reaching zero when `del y` was encountered.
+ Calling `globals` (or really, executing anything that will have a non `None` result) caused `_` to reference the new result, dropping the existing reference. Now the reference count reached 0 and we can see "Deleted!" being printed (finally!).

---

### ‚ñ∂ The out of scope variable
<!-- Example ID: 75c03015-7be9-4289-9e22-4f5fdda056f7 --->
```py
a = 1
def some_func():
    return a

def another_func():
    a += 1
    return a
```

**Output:**
```py
>>> some_func()
1
>>> another_func()
UnboundLocalError: local variable 'a' referenced before assignment
```

#### üí° Explanation:
* When you make an assignment to a variable in scope, it becomes local to that scope. So `a` becomes local to the scope of `another_func`,  but it has not been initialized previously in the same scope, which throws an error.
* Read [this](http://sebastianraschka.com/Articles/2014_python_scope_and_namespaces.html) short but an awesome guide to learn more about how namespaces and scope resolution works in Python.
* To modify the outer scope variable `a` in `another_func`, use `global` keyword.
  ```py
  def another_func()
      global a
      a += 1
      return a
  ```

  **Output:**
  ```py
  >>> another_func()
  2
  ```

---

### ‚ñ∂ Deleting a list item while iterating
<!-- Example ID: 4cc52d4e-d42b-4e09-b25f-fbf5699b7d4e --->
```py
list_1 = [1, 2, 3, 4]
list_2 = [1, 2, 3, 4]
list_3 = [1, 2, 3, 4]
list_4 = [1, 2, 3, 4]

for idx, item in enumerate(list_1):
    del item

for idx, item in enumerate(list_2):
    list_2.remove(item)

for idx, item in enumerate(list_3[:]):
    list_3.remove(item)

for idx, item in enumerate(list_4):
    list_4.pop(idx)
```

**Output:**
```py
>>> list_1
[1, 2, 3, 4]
>>> list_2
[2, 4]
>>> list_3
[]
>>> list_4
[2, 4]
```

Can you guess why the output is `[2, 4]`?

#### üí° Explanation:

* It's never a good idea to change the object you're iterating over. The correct way to do so is to iterate over a copy of the object instead, and `list_3[:]` does just that.

     ```py
     >>> some_list = [1, 2, 3, 4]
     >>> id(some_list)
     139798789457608
     >>> id(some_list[:]) # Notice that python creates new object for sliced list.
     139798779601192
     ```

**Difference between `del`, `remove`, and `pop`:**
* `del var_name` just removes the binding of the `var_name` from the local or global namespace (That's why the `list_1` is unaffected).
* `remove` removes the first matching value, not a specific index, raises `ValueError` if the value is not found.
* `pop` removes the element at a specific index and returns it, raises `IndexError` if an invalid index is specified.

**Why the output is `[2, 4]`?**
- The list iteration is done index by index, and when we remove `1` from `list_2` or `list_4`, the contents of the lists are now `[2, 3, 4]`. The remaining elements are shifted down, i.e., `2` is at index 0, and `3` is at index 1. Since the next iteration is going to look at index 1 (which is the `3`), the `2` gets skipped entirely. A similar thing will happen with every alternate element in the list sequence.

* Refer to this StackOverflow [thread](https://stackoverflow.com/questions/45946228/what-happens-when-you-try-to-delete-a-list-element-while-iterating-over-it) explaining the example
* See also this nice StackOverflow [thread](https://stackoverflow.com/questions/45877614/how-to-change-all-the-dictionary-keys-in-a-for-loop-with-d-items) for a similar example related to dictionaries in Python.

---


### ‚ñ∂ Lossy zip of iterators *
<!-- Example ID: c28ed154-e59f-4070-8eb6-8967a4acac6d --->

```py
>>> numbers = list(range(7))
>>> numbers
[0, 1, 2, 3, 4, 5, 6]
>>> first_three, remaining = numbers[:3], numbers[3:]
>>> first_three, remaining
([0, 1, 2], [3, 4, 5, 6])
>>> numbers_iter = iter(numbers)
>>> list(zip(numbers_iter, first_three)) 
[(0, 0), (1, 1), (2, 2)]
# so far so good, let's zip the remaining
>>> list(zip(numbers_iter, remaining))
[(4, 3), (5, 4), (6, 5)]
```
Where did element `3` go from the `numbers` list?

#### üí° Explanation:

- From Python [docs](https://docs.python.org/3.3/library/functions.html#zip), here's an approximate implementation of zip function,
    ```py
    def zip(*iterables):
        sentinel = object()
        iterators = [iter(it) for it in iterables]
        while iterators:
            result = []
            for it in iterators:
                elem = next(it, sentinel)
                if elem is sentinel: return
                result.append(elem)
            yield tuple(result)
    ```
- So the function takes in arbitrary number of iterable objects, adds each of their items to the `result` list by calling the `next` function on them, and stops whenever any of the iterable is exhausted. 
- The caveat here is when any iterable is exhausted, the existing elements in the `result` list are discarded. That's what happened with `3` in the `numbers_iter`.
- The correct way to do the above using `zip` would be,
    ```py
    >>> numbers = list(range(7))
    >>> numbers_iter = iter(numbers)
    >>> list(zip(first_three, numbers_iter))
    [(0, 0), (1, 1), (2, 2)]
    >>> list(zip(remaining, numbers_iter))
    [(3, 3), (4, 4), (5, 5), (6, 6)]
    ```
    The first argument of zip should be the one with fewest elements.

---

### ‚ñ∂ Loop variables leaking out!
<!-- Example ID: ccec7bf6-7679-4963-907a-1cd8587be9ea --->
1\.
```py
for x in range(7):
    if x == 6:
        print(x, ': for x inside loop')
print(x, ': x in global')
```

**Output:**
```py
6 : for x inside loop
6 : x in global
```

But `x` was never defined outside the scope of for loop...

2\.
```py
# This time let's initialize x first
x = -1
for x in range(7):
    if x == 6:
        print(x, ': for x inside loop')
print(x, ': x in global')
```

**Output:**
```py
6 : for x inside loop
6 : x in global
```

3\.

**Output (Python 2.x):**
```py
>>> x = 1
>>> print([x for x in range(5)])
[0, 1, 2, 3, 4]
>>> print(x)
4
```

**Output (Python 3.x):**
```py
>>> x = 1
>>> print([x for x in range(5)])
[0, 1, 2, 3, 4]
>>> print(x)
1
```

#### üí° Explanation:

- In Python, for-loops use the scope they exist in and leave their defined loop-variable behind. This also applies if we explicitly defined the for-loop variable in the global namespace before. In this case, it will rebind the existing variable.

- The differences in the output of Python 2.x and Python 3.x interpreters for list comprehension example can be explained by following change documented in [What‚Äôs New In Python 3.0](https://docs.python.org/3/whatsnew/3.0.html) changelog:

    > "List comprehensions no longer support the syntactic form `[... for var in item1, item2, ...]`. Use `[... for var in (item1, item2, ...)]` instead. Also, note that list comprehensions have different semantics: they are closer to syntactic sugar for a generator expression inside a `list()` constructor, and in particular, the loop control variables are no longer leaked into the surrounding scope."

---

### ‚ñ∂ Beware of default mutable arguments!
<!-- Example ID: 7d42dade-e20d-4a7b-9ed7-16fb58505fe9 --->

```py
def some_func(default_arg=[]):
    default_arg.append("some_string")
    return default_arg
```

**Output:**
```py
>>> some_func()
['some_string']
>>> some_func()
['some_string', 'some_string']
>>> some_func([])
['some_string']
>>> some_func()
['some_string', 'some_string', 'some_string']
```

#### üí° Explanation:

- The default mutable arguments of functions in Python aren't really initialized every time you call the function. Instead, the recently assigned value to them is used as the default value. When we explicitly passed `[]` to `some_func` as the argument, the default value of the `default_arg` variable was not used, so the function returned as expected.

    ```py
    def some_func(default_arg=[]):
        default_arg.append("some_string")
        return default_arg
    ```

    **Output:**
    ```py
    >>> some_func.__defaults__ #This will show the default argument values for the function
    ([],)
    >>> some_func()
    >>> some_func.__defaults__
    (['some_string'],)
    >>> some_func()
    >>> some_func.__defaults__
    (['some_string', 'some_string'],)
    >>> some_func([])
    >>> some_func.__defaults__
    (['some_string', 'some_string'],)
    ```

- A common practice to avoid bugs due to mutable arguments is to assign `None` as the default value and later check if any value is passed to the function corresponding to that argument. Example:

    ```py
    def some_func(default_arg=None):
        if default_arg is None:
            default_arg = []
        default_arg.append("some_string")
        return default_arg
    ```

---

### ‚ñ∂ Catching the Exceptions
<!-- Example ID: b5ca5e6a-47b9-4f69-9375-cda0f8c6755d --->
```py
some_list = [1, 2, 3]
try:
    # This should raise an ``IndexError``
    print(some_list[4])
except IndexError, ValueError:
    print("Caught!")

try:
    # This should raise a ``ValueError``
    some_list.remove(4)
except IndexError, ValueError:
    print("Caught again!")
```

**Output (Python 2.x):**
```py
Caught!

ValueError: list.remove(x): x not in list
```

**Output (Python 3.x):**
```py
  File "<input>", line 3
    except IndexError, ValueError:
                     ^
SyntaxError: invalid syntax
```

#### üí° Explanation

* To add multiple Exceptions to the except clause, you need to pass them as parenthesized tuple as the first argument. The second argument is an optional name, which when supplied will bind the Exception instance that has been raised. Example,
  ```py
  some_list = [1, 2, 3]
  try:
     # This should raise a ``ValueError``
     some_list.remove(4)
  except (IndexError, ValueError), e:
     print("Caught again!")
     print(e)
  ```
  **Output (Python 2.x):**
  ```
  Caught again!
  list.remove(x): x not in list
  ```
  **Output (Python 3.x):**
  ```py
    File "<input>", line 4
      except (IndexError, ValueError), e:
                                       ^
  IndentationError: unindent does not match any outer indentation level
  ```

* Separating the exception from the variable with a comma is deprecated and does not work in Python 3; the correct way is to use `as`. Example,
  ```py
  some_list = [1, 2, 3]
  try:
      some_list.remove(4)

  except (IndexError, ValueError) as e:
      print("Caught again!")
      print(e)
  ```
  **Output:**
  ```
  Caught again!
  list.remove(x): x not in list
  ```

---

### ‚ñ∂ Same operands, different story!
<!-- Example ID: ca052cdf-dd2d-4105-b936-65c28adc18a0 --->
1\.
```py
a = [1, 2, 3, 4]
b = a
a = a + [5, 6, 7, 8]
```

**Output:**
```py
>>> a
[1, 2, 3, 4, 5, 6, 7, 8]
>>> b
[1, 2, 3, 4]
```

2\.
```py
a = [1, 2, 3, 4]
b = a
a += [5, 6, 7, 8]
```

**Output:**
```py
>>> a
[1, 2, 3, 4, 5, 6, 7, 8]
>>> b
[1, 2, 3, 4, 5, 6, 7, 8]
```

#### üí° Explanation:

*  `a += b` doesn't always behave the same way as `a = a + b`.  Classes *may* implement the *`op=`* operators differently, and lists do this.

* The expression `a = a + [5,6,7,8]` generates a new list and sets `a`'s reference to that new list, leaving `b` unchanged.

* The expression `a += [5,6,7,8]` is actually mapped to an "extend" function that operates on the list such that `a` and `b` still point to the same list that has been modified in-place.

---

### ‚ñ∂ Name resolution ignoring class scope
<!-- Example ID: 03f73d96-151c-4929-b0a8-f74430788324 --->
1\.
```py
x = 5
class SomeClass:
    x = 17
    y = (x for i in range(10))
```

**Output:**
```py
>>> list(SomeClass.y)[0]
5
```

2\.
```py
x = 5
class SomeClass:
    x = 17
    y = [x for i in range(10)]
```

**Output (Python 2.x):**
```py
>>> SomeClass.y[0]
17
```

**Output (Python 3.x):**
```py
>>> SomeClass.y[0]
5
```

#### üí° Explanation
- Scopes nested inside class definition ignore names bound at the class level.
- A generator expression has its own scope.
- Starting from Python 3.X, list comprehensions also have their own scope.

---

### ‚ñ∂ Needles in a Haystack *

<!-- Example ID: 52a199b1-989a-4b28-8910-dff562cebba9 --->

I haven't met even a single experience Pythonist till date who has not come across one or more of the following scenarios,

1\.

```py
x, y = (0, 1) if True else None, None
```

**Output:**

```py
>>> x, y  # expected (0, 1)
((0, 1), None)
```

2\.

```py
t = ('one', 'two')
for i in t:
    print(i)

t = ('one')
for i in t:
    print(i)

t = ()
print(t)
```

**Output:**

```py
one
two
o
n
e
tuple()
```

3\.

```
ten_words_list = [
    "some",
    "very",
    "big",
    "list",
    "that"
    "consists",
    "of",
    "exactly",
    "ten",
    "words"
]
```

**Output**

```py
>>> len(ten_words_list)
9
```

4\. Not asserting strongly enough

```py
a = "python"
b = "javascript"
```

**Output:**

```py
# An assert statement with an assertion failure message.
>>> assert(a == b, "Both languages are different")
# No AssertionError is raised
```

5\.

```py
some_list = [1, 2, 3]
some_dict = {
  "key_1": 1,
  "key_2": 2,
  "key_3": 3
}

some_list = some_list.append(4) 
some_dict = some_dict.update({"key_4": 4})
```

**Output:**

```py
>>> print(some_list)
None
>>> print(some_dict)
None
```

6\.

```py
def some_recursive_func(a):
    if a[0] == 0:
        return 
    a[0] -= 1
    some_recursive_func(a)
    return a

def similar_recursive_func(a):
        if a == 0:
                return a
        a -= 1
        similar_recursive_func(a)
        return a
```

**Output:**

```py
>>> some_recursive_func([5, 0])
[0, 0]
>>> similar_recursive_func(5)
4
```

#### üí° Explanation:

* For 1, the correct statement for expected behavior is `x, y = (0, 1) if True else (None, None)`.

* For 2, the correct statement for expected behavior is `t = ('one',)` or `t = 'one',` (missing comma) otherwise the interpreter considers `t` to be a `str` and iterates over it character by character.

* `()` is a special token and denotes empty `tuple`.

* In 3, as you might have already figured out, there's a missing comma after 5th element (`"that"`) in the list. So by implicit string literal concatenation,

  ```py
  >>> ten_words_list
  ['some', 'very', 'big', 'list', 'thatconsists', 'of', 'exactly', 'ten', 'words']
  ```

* No `AssertionError` was raised in 4th snippet because instead of asserting the individual expression `a == b`, we're asserting entire tuple. The following snippet will clear things up,

  ```py
  >>> a = "python"
  >>> b = "javascript"
  >>> assert a == b
  Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
  AssertionError
  
  >>> assert (a == b, "Values are not equal")
  <stdin>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  
  >>> assert a == b, "Values are not equal"
  Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
  AssertionError: Values are not equal
  ```

* As for the fifth snippet, most methods that modify the items of sequence/mapping objects like `list.append`, `dict.update`, `list.sort`, etc. modify the objects in-place and return `None`. The rationale behind this is to improve performance by avoiding making a copy of the object if the operation can be done in-place (Referred from [here](http://docs.python.org/2/faq/design.html#why-doesn-t-list-sort-return-the-sorted-list)).

* Last one should be fairly obvious, mutable object (like `list`) can be altered in the function, and the reassignation of an immutable (`a -= 1`) is not an alteration of the value.

* Being aware of these nitpicks can save you hours of debugging effort in the long run. 

---


### ‚ñ∂ Splitsies *
<!-- Example ID: ec3168ba-a81a-4482-afb0-691f1cc8d65a --->
```py
>>> 'a'.split()
['a']

# is same as
>>> 'a'.split(' ')
['a']

# but
>>> len(''.split())
0

# isn't the same as
>>> len(''.split(' '))
1
```

#### üí° Explanation:

- It might appear at first that the default separator for split is a single space `' '`, but as per the [docs](https://docs.python.org/2.7/library/stdtypes.html#str.split)
    >  If sep is not specified or is `None`, a different splitting algorithm is applied: runs of consecutive whitespace are regarded as a single separator, and the result will contain no empty strings at the start or end if the string has leading or trailing whitespace. Consequently, splitting an empty string or a string consisting of just whitespace with a None separator returns `[]`.
    > If sep is given, consecutive delimiters are not grouped together and are deemed to delimit empty strings (for example, `'1,,2'.split(',')` returns `['1', '', '2']`). Splitting an empty string with a specified separator returns `['']`.
- Noticing how the leading and trailing whitespaces are handled in the following snippet will make things clear,
    ```py
    >>> ' a '.split(' ')
    ['', 'a', '']
    >>> ' a '.split()
    ['a']
    >>> ''.split(' ')
    ['']
    ```

---

### ‚ñ∂ Wild imports *
<!-- Example ID: 83deb561-bd55-4461-bb5e-77dd7f411e1c --->
<!-- read-only -->

```py
# File: module.py

def some_weird_name_func_():
    print("works!")

def _another_weird_name_func():
    print("works!")

```

**Output**

```py
>>> from module import *
>>> some_weird_name_func_()
"works!"
>>> _another_weird_name_func()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '_another_weird_name_func' is not defined
```

#### üí° Explanation:

- It is often advisable to not use wildcard imports. The first obvious reason for this is, in wildcard imports, the names with a leading underscore don't get imported. This may lead to errors during runtime.
- Had we used `from ... import a, b, c` syntax, the above `NameError` wouldn't have occurred.
    ```py
    >>> from module import some_weird_name_func_, _another_weird_name_func
    >>> _another_weird_name_func()
    works!
    ```
- If you really want to use wildcard imports, then you'd have to define the list `__all__` in your module that will contain a list of public objects that'll be available when we do wildcard imports.
    ```py
    __all__ = ['_another_weird_name_func']

    def some_weird_name_func_():
        print("works!")

    def _another_weird_name_func():
        print("works!")
    ```
    **Output**

    ```py
    >>> _another_weird_name_func()
    "works!"
    >>> some_weird_name_func_()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    NameError: name 'some_weird_name_func_' is not defined
    ```

---

### ‚ñ∂ All sorted? *

<!-- Example ID: e5ff1eaf-8823-4738-b4ce-b73f7c9d5511 -->

```py
>>> x = 7, 8, 9
>>> sorted(x) == x
False
>>> sorted(x) == sorted(x)
True

>>> y = reversed(x)
>>> sorted(y) == sorted(y)
False
```

#### üí° Explanation:

- The `sorted` method always returns a list, and comparing lists and tuples always returns `False` in Python. 

- ```py
  >>> [] == tuple()
  False
  >>> x = 7, 8, 9
  >>> type(x), type(sorted(x))
  (tuple, list)
  ```

- Unlike `sorted`, the `reversed` method returns an iterator. Why? Because sorting requires the iterator to be either modified in-place or use an extra container (a list), whereas reversing can simply work by iterating from the last index to the first.

- So during comparison `sorted(y) == sorted(y)`, the first call to `sorted()` will consume the iterator `y`, and the next call will just return an empty list.

  ```py
  >>> x = 7, 8, 9
  >>> y = reversed(x)
  >>> sorted(y), sorted(y)
  ([7, 8, 9], [])
  ```

---

### ‚ñ∂ Midnight time doesn't exist?
<!-- Example ID: 1bce8294-5619-4d70-8ce3-fe0bade690d1 --->
```py
from datetime import datetime

midnight = datetime(2018, 1, 1, 0, 0)
midnight_time = midnight.time()

noon = datetime(2018, 1, 1, 12, 0)
noon_time = noon.time()

if midnight_time:
    print("Time at midnight is", midnight_time)

if noon_time:
    print("Time at noon is", noon_time)
```

**Output (< 3.5):**

```py
('Time at noon is', datetime.time(12, 0))
```
The midnight time is not printed.

#### üí° Explanation:

Before Python 3.5, the boolean value for `datetime.time` object was considered to be `False` if it represented midnight in UTC. It is error-prone when using the `if obj:` syntax to check if the `obj` is null or some equivalent of "empty."

---
---



## Section: The Hidden treasures!

This section contains a few lesser-known and interesting things about Python that most beginners like me are unaware of (well, not anymore).

### ‚ñ∂ Okay Python, Can you make me fly?
<!-- Example ID: a92f3645-1899-4d50-9721-0031be4aec3f --->
Well, here you go

```py
import antigravity
```

**Output:**
Sshh... It's a super-secret.

#### üí° Explanation:
+ `antigravity` module is one of the few easter eggs released by Python developers.
+ `import antigravity` opens up a web browser pointing to the [classic XKCD comic](http://xkcd.com/353/) about Python.
+ Well, there's more to it. There's **another easter egg inside the easter egg**. If you look at the [code](https://github.com/python/cpython/blob/master/Lib/antigravity.py#L7-L17), there's a function defined that purports to implement the [XKCD's geohashing algorithm](https://xkcd.com/426/).

---

### ‚ñ∂ `goto`, but why?
<!-- Example ID: 2aff961e-7fa5-4986-a18a-9e5894bd89fe --->

```py
from goto import goto, label
for i in range(9):
    for j in range(9):
        for k in range(9):
            print("I am trapped, please rescue!")
            if k == 2:
                goto .breakout # breaking out from a deeply nested loop
label .breakout
print("Freedom!")
```

**Output (Python 2.3):**
```py
I am trapped, please rescue!
I am trapped, please rescue!
Freedom!
```

#### üí° Explanation:
- A working version of `goto` in Python was [announced](https://mail.python.org/pipermail/python-announce-list/2004-April/002982.html) as an April Fool's joke on 1st April 2004.
- Current versions of Python do not have this module.
- Although it works, but please don't use it. Here's the [reason](https://docs.python.org/3/faq/design.html#why-is-there-no-goto) to why `goto` is not present in Python.

---

### ‚ñ∂ Brace yourself!
<!-- Example ID: 5c0c75f2-ddd9-4da3-ba49-c4be7ec39acf --->
If you are one of the people who doesn't like using whitespace in Python to denote scopes, you can use the C-style {} by importing,

```py
from __future__ import braces
```

**Output:**
```py
  File "some_file.py", line 1
    from __future__ import braces
SyntaxError: not a chance
```

Braces? No way! If you think that's disappointing, use Java. Okay, another surprising thing, can you find where's the `SyntaxError` raised in `__future__` module [code](https://github.com/python/cpython/blob/master/Lib/__future__.py)?

#### üí° Explanation:
+ The `__future__` module is normally used to provide features from future versions of Python. The "future" in this specific context is however, ironic.
+ This is an easter egg concerned with the community's feelings on this issue.
+ The code is actually present [here](https://github.com/python/cpython/blob/025eb98dc0c1dc27404df6c544fc2944e0fa9f3a/Python/future.c#L49) in `future.c` file.
+ When the CPython compiler encounters a [future statement](https://docs.python.org/3.3/reference/simple_stmts.html#future-statements), it first runs the appropriate code in `future.c` before treating it as a normal import statement.

---

### ‚ñ∂ Let's meet Friendly Language Uncle For Life
<!-- Example ID: 6427fae6-e959-462d-85da-ce4c94ce41be --->
**Output (Python 3.x)**
```py
>>> from __future__ import barry_as_FLUFL
>>> "Ruby" != "Python" # there's no doubt about it
  File "some_file.py", line 1
    "Ruby" != "Python"
              ^
SyntaxError: invalid syntax

>>> "Ruby" <> "Python"
True
```

There we go.

#### üí° Explanation:
- This is relevant to [PEP-401](https://www.python.org/dev/peps/pep-0401/) released on April 1, 2009 (now you know, what it means).
- Quoting from the PEP-401
  
  > Recognized that the != inequality operator in Python 3.0 was a horrible, finger-pain inducing mistake, the FLUFL reinstates the <> diamond operator as the sole spelling.
- There were more things that Uncle Barry had to share in the PEP; you can read them [here](https://www.python.org/dev/peps/pep-0401/).
- It works well in an interactive environment, but it will raise a `SyntaxError` when you run via python file (see this [issue](https://github.com/satwikkansal/wtfpython/issues/94)). However, you can wrap the statement inside an `eval` or `compile` to get it working,
    ```py
    from __future__ import barry_as_FLUFL
    print(eval('"Ruby" <> "Python"'))
    ```

---

### ‚ñ∂ Even Python understands that love is complicated
<!-- Example ID: b93cad9e-d341-45d1-999c-fcdce65bed25 --->
```py
import this
```

Wait, what's **this**? `this` is love :heart:

**Output:**
```
The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
```

It's the Zen of Python!

```py
>>> love = this
>>> this is love
True
>>> love is True
False
>>> love is False
False
>>> love is not True or False
True
>>> love is not True or False; love is love  # Love is complicated
True
```

#### üí° Explanation:

* `this` module in Python is an easter egg for The Zen Of Python ([PEP 20](https://www.python.org/dev/peps/pep-0020)).
* And if you think that's already interesting enough, check out the implementation of [this.py](https://hg.python.org/cpython/file/c3896275c0f6/Lib/this.py). Interestingly, **the code for the Zen violates itself** (and that's probably the only place where this happens).
* Regarding the statement `love is not True or False; love is love`, ironic but it's self-explanatory (if not, please see the examples related to `is` and `is not` operators).

---

### ‚ñ∂ Yes, it exists!
<!-- Example ID: 4286db3d-1ea7-47c9-8fb6-a9a04cac6e49 --->
**The `else` clause for loops.** One typical example might be:

```py
  def does_exists_num(l, to_find):
      for num in l:
          if num == to_find:
              print("Exists!")
              break
      else:
          print("Does not exist")
```

**Output:**
```py
>>> some_list = [1, 2, 3, 4, 5]
>>> does_exists_num(some_list, 4)
Exists!
>>> does_exists_num(some_list, -1)
Does not exist
```

**The `else` clause in exception handling.** An example,

```py
try:
    pass
except:
    print("Exception occurred!!!")
else:
    print("Try block executed successfully...")
```

**Output:**
```py
Try block executed successfully...
```

#### üí° Explanation:
- The `else` clause after a loop is executed only when there's no explicit `break` after all the iterations. You can think of it as a "nobreak" clause.
- `else` clause after a try block is also called "completion clause" as reaching the `else` clause in a `try` statement means that the try block actually completed successfully.

---
### ‚ñ∂ Ellipsis *
<!-- Example ID: 969b7100-ab3d-4a7d-ad7d-a6be16181b2b --->
```py
def some_func():
    Ellipsis
```

**Output**
```py
>>> some_func()
# No output, No Error

>>> SomeRandomString
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'SomeRandomString' is not defined

>>> Ellipsis
Ellipsis
```

#### üí° Explanation
- In Python, `Ellipsis` is a globally available built-in object which is equivalent to `...`.
    ```py
    >>> ...
    Ellipsis
    ```
- Eliipsis can be used for several purposes,
    + As a placeholder for code that hasn't been written yet (just like `pass` statement)
    + In slicing syntax to represent the full slices in remaining direction
    ```py
    >>> import numpy as np
    >>> three_dimensional_array = np.arange(8).reshape(2, 2, 2)
    array([
        [
            [0, 1],
            [2, 3]
        ],

        [
            [4, 5],
            [6, 7]
        ]
    ])
    ```
    So our `three_dimensional_array` is an array of array of arrays. Let's say we want to print the second element (index `1`) of all the innermost arrays, we can use Ellipsis to bypass all the preceding dimensions
    ```py
    >>> three_dimensional_array[:,:,1]
    array([[1, 3],
       [5, 7]])
    >>> three_dimensional_array[..., 1] # using Ellipsis.
    array([[1, 3],
       [5, 7]])
    ```
    Note: this will work for any number of dimensions. You can even select slice in first and last dimension and ignore the middle ones this way (`n_dimensional_array[firs_dim_slice, ..., last_dim_slice]`)
    + In [type hinting](https://docs.python.org/3/library/typing.html) to indicate only a part of the type (like `(Callable[..., int]` or `Tuple[str, ...]`))
    + You may also use Ellipsis as a default function argument (in the cases when you want to differentiate between the "no argument passed" and "None value passed" scenarios).

---

### ‚ñ∂ Inpinity
<!-- Example ID: ff473ea8-a3b1-4876-a6f0-4378aff790c1 --->
The spelling is intended. Please, don't submit a patch for this.

**Output (Python 3.x):**
```py
>>> infinity = float('infinity')
>>> hash(infinity)
314159
>>> hash(float('-inf'))
-314159
```

#### üí° Explanation:
- Hash of infinity is 10‚Åµ x œÄ.
- Interestingly, the hash of `float('-inf')` is "-10‚Åµ x œÄ" in Python 3, whereas "-10‚Åµ x e" in Python 2.

---

### ‚ñ∂ Let's mangle
<!-- Example ID: 37146d2d-9e67-43a9-8729-3c17934b910c --->
1\.
```py
class Yo(object):
    def __init__(self):
        self.__honey = True
        self.bro = True
```

**Output:**
```py
>>> Yo().bro
True
>>> Yo().__honey
AttributeError: 'Yo' object has no attribute '__honey'
>>> Yo()._Yo__honey
True
```

2\.
```py
class Yo(object):
    def __init__(self):
        # Let's try something symmetrical this time
        self.__honey__ = True
        self.bro = True
```

**Output:**
```py
>>> Yo().bro
True

>>> Yo()._Yo__honey__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Yo' object has no attribute '_Yo__honey__'
```

Why did `Yo()._Yo__honey` work?

3\.

```py
_A__variable = "Some value"

class A(object):
    def some_func(self):
        return __variable # not initialized anywhere yet
```

**Output:**
```py
>>> A().__variable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'A' object has no attribute '__variable'

>>> A().some_func()
'Some value'
```


#### üí° Explanation:

* [Name Mangling](https://en.wikipedia.org/wiki/Name_mangling) is used to avoid naming collisions between different namespaces.
* In Python, the interpreter modifies (mangles) the class member names starting with `__` (double underscore a.k.a "dunder") and not ending with more than one trailing underscore by adding `_NameOfTheClass` in front.
* So, to access `__honey` attribute in the first snippet, we had to append `_Yo` to the front, which would prevent conflicts with the same name attribute defined in any other class.
* But then why didn't it work in the second snippet? Because name mangling excludes the names ending with double underscores.
* The third snippet was also a consequence of name mangling. The name `__variable` in the statement `return __variable` was mangled to `_A__variable`, which also happens to be the name of the variable we declared in the outer scope.
* Also, if the mangled name is longer than 255 characters, truncation will happen.

---
---

## Section: Appearances are deceptive!

### ‚ñ∂ Skipping lines?
<!-- Example ID: d50bbde1-fb9d-4735-9633-3444b9d2f417 --->
**K·∫øt qu·∫£:**
```py
>>> value = 11
>>> valu–µ = 32
>>> value
11
```

C√°i qu√°i g√¨ th·∫ø?

**Ch√∫ √Ω:** ƒê·ªÉ l√†m ra k·∫øt qu·∫£ nh∆∞ tr√™n b·∫°n ch·ªâ c·∫ßn sao ch·∫øp c√°c c√¢u l·ªánh v√† d√°n n√≥ v√†o file hay shell.

#### üí° Gi·∫£i th√≠ch

Some non-Western characters look identical to letters in the English alphabet but are considered distinct by the interpreter.
M·ªôt v√†i k√≠ t·ª± kh√¥ng ph·∫£i l√† k√≠ t·ª± ph∆∞∆°ng t√¢y tr√¥ng gi·ªëng nh∆∞ c√°c k√≠ t·ª± trong b·∫£ng ch·ªØ c√°i ti·∫øng Anh nh∆∞ng l·∫°i ƒë∆∞·ª£c di·ªÖn gi·∫£i kh√°c b·ªüi tr√¨nh th√¥ng idhcj
```py
>>> ord('–µ') # K√≠ t·ª± cyrillic 'e' (Ye)
1077
>>> ord('e') # K√≠ t·ª± latin 'e', ƒë∆∞·ª£c s·ª≠ d·ª•ng trong ti·∫øng Anh v√† tr√™n c√°c b√†n ph√≠m chu·∫©n
101
>>> '–µ' == 'e'
False

>>> value = 42 # latin e
>>> valu–µ = 23 # cyrillic 'e', Python 2.x interpreter would raise a `SyntaxError` here
>>> value
42
```

H√†m t√≠ch h·ª£p s·∫µn `ord()` function returns a character's Unicode [code point](https://en.wikipedia.org/wiki/Code_point), and different code positions of Cyrillic 'e' and Latin 'e' justify the behavior of the above example.

H√†m t√≠ch h·ª£p s·∫µn `ord()` tr·∫£ v·ªÅ m√£ Unicode c·ªßa m·ªôt k√≠ t·ª± [code point](https://en.wikipedia.org/wiki/Code_point), v√† b·∫°n c√≥ th·ªÉ th·∫•y c√°c m√£ kh√°c nhau cho k√≠ t·ª±  Cyrillic 'e' v√† k√≠ t·ª± Latin 'e' .

---

### ‚ñ∂ Teleportation

<!-- Example ID: edafe923-0c20-4315-b6e1-0c31abfc38f5 --->

```py
# `pip install numpy` first.
import numpy as np

def energy_send(x):
    # Initializing a numpy array
    np.array([float(x)])

def energy_receive():
    # Return an empty numpy array
    return np.empty((), dtype=np.float).tolist()
```

**Output:**
```py
>>> energy_send(123.456)
>>> energy_receive()
123.456
```

Where's the Nobel Prize?

#### üí° Explanation:

* Notice that the numpy array created in the `energy_send` function is not returned, so that memory space is free to reallocate.
* `numpy.empty()` returns the next free memory slot without reinitializing it. This memory spot just happens to be the same one that was just freed (usually, but not always).

---

### ‚ñ∂ Well, something is fishy...
<!-- Example ID: cb6a37c5-74f7-44ca-b58c-3b902419b362 --->
```py
def square(x):
    """
    A simple function to calculate the square of a number by addition.
    """
    sum_so_far = 0
    for counter in range(x):
        sum_so_far = sum_so_far + x
  return sum_so_far
```

**Output (Python 2.x):**

```py
>>> square(10)
10
```

Shouldn't that be 100?

**Note:** If you're not able to reproduce this, try running the file [mixed_tabs_and_spaces.py](/mixed_tabs_and_spaces.py) via the shell.

#### üí° Explanation

* **Don't mix tabs and spaces!** The character just preceding return is a "tab",  and the code is indented by multiple of "4 spaces" elsewhere in the example.
* This is how Python handles tabs:
  
  > First, tabs are replaced (from left to right) by one to eight spaces such that the total number of characters up to and including the replacement is a multiple of eight <...>
* So the "tab" at the last line of `square` function is replaced with eight spaces, and it gets into the loop.
* Python 3 is kind enough to throw an error for such cases automatically.

    **Output (Python 3.x):**
    ```py
    TabError: inconsistent use of tabs and spaces in indentation
    ```

---
---

## Section: Miscellaneous


### ‚ñ∂ `+=` nhanh h∆°n
<!-- Example ID: bfd19c60-a807-4a26-9598-4912b86ddb36 --->

```py
# S·ª≠ d·ª•ng "+" ƒë·ªÉ c·ªông 3 strings:
>>> timeit.timeit("s1 = s1 + s2 + s3", setup="s1 = ' ' * 100000; s2 = ' ' * 100000; s3 = ' ' * 100000", number=100)
0.25748300552368164
# S·ª≠ d·ª•ng "+=" ƒë·ªÉ c·ªông 3 strings:
>>> timeit.timeit("s1 += s2 + s3", setup="s1 = ' ' * 100000; s2 = ' ' * 100000; s3 = ' ' * 100000", number=100)
0.012188911437988281
```

#### üí° Gi·∫£i th√≠ch:
+ `+=` nhanh h∆°n `+` for concatenating more than two strings because the first string (example, `s1` for `s1 += s2 + s3`) is not destroyed while calculating the complete string.
+ `+=` nhanh h∆°n `+` khi n·ªëi nhi·ªÅu h∆°n 2 strings b·ªüi v√¨ string ƒë·∫ßu ti√™n (v√≠ d·ª•, `s1` trong `s1 += s2 + s3`) kh√¥ng b·ªã hu·ª∑ ƒëi khi t·∫°o ra chu·ªói k·∫øt qu·∫£ cu·ªëi c√πng
---

### ‚ñ∂ Let's make a giant string!
<!-- Example ID: c7a07424-63fe-4504-9842-8f3d334f28fc --->
```py
def add_string_with_plus(iters):
    s = ""
    for i in range(iters):
        s += "xyz"
    assert len(s) == 3*iters

def add_bytes_with_plus(iters):
    s = b""
    for i in range(iters):
        s += b"xyz"
    assert len(s) == 3*iters

def add_string_with_format(iters):
    fs = "{}"*iters
    s = fs.format(*(["xyz"]*iters))
    assert len(s) == 3*iters

def add_string_with_join(iters):
    l = []
    for i in range(iters):
        l.append("xyz")
    s = "".join(l)
    assert len(s) == 3*iters

def convert_list_to_string(l, iters):
    s = "".join(l)
    assert len(s) == 3*iters
```

**Output:**

```py
# Executed in ipython shell using %timeit for better readability of results.
# You can also use the timeit module in normal python shell/scriptm=, example usage below
# timeit.timeit('add_string_with_plus(10000)', number=1000, globals=globals())

>>> NUM_ITERS = 1000
>>> %timeit -n1000 add_string_with_plus(NUM_ITERS)
124 ¬µs ¬± 4.73 ¬µs per loop (mean ¬± std. dev. of 7 runs, 100 loops each)
>>> %timeit -n1000 add_bytes_with_plus(NUM_ITERS)
211 ¬µs ¬± 10.5 ¬µs per loop (mean ¬± std. dev. of 7 runs, 1000 loops each)
>>> %timeit -n1000 add_string_with_format(NUM_ITERS)
61 ¬µs ¬± 2.18 ¬µs per loop (mean ¬± std. dev. of 7 runs, 1000 loops each)
>>> %timeit -n1000 add_string_with_join(NUM_ITERS)
117 ¬µs ¬± 3.21 ¬µs per loop (mean ¬± std. dev. of 7 runs, 1000 loops each)
>>> l = ["xyz"]*NUM_ITERS
>>> %timeit -n1000 convert_list_to_string(l, NUM_ITERS)
10.1 ¬µs ¬± 1.06 ¬µs per loop (mean ¬± std. dev. of 7 runs, 1000 loops each)
```

Let's increase the number of iterations by a factor of 10.

```py
>>> NUM_ITERS = 10000
>>> %timeit -n1000 add_string_with_plus(NUM_ITERS) # Linear increase in execution time
1.26 ms ¬± 76.8 ¬µs per loop (mean ¬± std. dev. of 7 runs, 1000 loops each)
>>> %timeit -n1000 add_bytes_with_plus(NUM_ITERS) # Quadratic increase
6.82 ms ¬± 134 ¬µs per loop (mean ¬± std. dev. of 7 runs, 1000 loops each)
>>> %timeit -n1000 add_string_with_format(NUM_ITERS) # Linear increase
645 ¬µs ¬± 24.5 ¬µs per loop (mean ¬± std. dev. of 7 runs, 1000 loops each)
>>> %timeit -n1000 add_string_with_join(NUM_ITERS) # Linear increase
1.17 ms ¬± 7.25 ¬µs per loop (mean ¬± std. dev. of 7 runs, 1000 loops each)
>>> l = ["xyz"]*NUM_ITERS
>>> %timeit -n1000 convert_list_to_string(l, NUM_ITERS) # Linear increase
86.3 ¬µs ¬± 2 ¬µs per loop (mean ¬± std. dev. of 7 runs, 1000 loops each)
```

#### üí° Explanation
- You can read more about [timeit](https://docs.python.org/3/library/timeit.html) or [%timeit](https://ipython.org/ipython-doc/dev/interactive/magics.html#magic-timeit) on these links. They are used to measure the execution time of code pieces.
- Don't use `+` for generating long strings ‚Äî In Python, `str` is immutable, so the left and right strings have to be copied into the new string for every pair of concatenations. If you concatenate four strings of length 10, you'll be copying (10+10) + ((10+10)+10) + (((10+10)+10)+10) = 90 characters instead of just 40 characters. Things get quadratically worse as the number and size of the string increases (justified with the execution times of `add_bytes_with_plus` function)
- Therefore, it's advised to use `.format.` or `%` syntax (however, they are slightly slower than `+` for very short strings).
- Or better, if already you've contents available in the form of an iterable object, then use `''.join(iterable_object)` which is much faster.
- Unlike `add_bytes_with_plus` because of the `+=` optimizations discussed in the previous example, `add_string_with_plus` didn't show a quadratic increase in execution time. Had the statement been `s = s + "x" + "y" + "z"` instead of `s += "xyz"`, the increase would have been quadratic.
  ```py
  def add_string_with_plus(iters):
      s = ""
      for i in range(iters):
          s = s + "x" + "y" + "z"
      assert len(s) == 3*iters

  >>> %timeit -n100 add_string_with_plus(1000)
  388 ¬µs ¬± 22.4 ¬µs per loop (mean ¬± std. dev. of 7 runs, 1000 loops each)
  >>> %timeit -n100 add_string_with_plus(10000) # Quadratic increase in execution time
  9 ms ¬± 298 ¬µs per loop (mean ¬± std. dev. of 7 runs, 100 loops each)
  ```
- So many ways to format and create a giant string are somewhat in contrast to the [Zen of Python](https://www.python.org/dev/peps/pep-0020/), according to which,
  
    > There should be one-- and preferably only one --obvious way to do it.

---

### ‚ñ∂ Minor Ones *
<!-- Example ID: f885cb82-f1e4-4daa-9ff3-972b14cb1324 --->
* `join()` is a string operation instead of list operation. (sort of counter-intuitive at first usage)

  **üí° Explanation:** If `join()` is a method on a string, then it can operate on any iterable (list, tuple, iterators). If it were a method on a list, it'd have to be implemented separately by every type. Also, it doesn't make much sense to put a string-specific method on a generic `list` object API.
  
* Few weird looking but semantically correct statements:
  + `[] = ()` is a semantically correct statement (unpacking an empty `tuple` into an empty `list`)
  + `'a'[0][0][0][0][0]` is also a semantically correct statement as strings are [sequences](https://docs.python.org/3/glossary.html#term-sequence)(iterables supporting element access using integer indices) in Python.
  + `3 --0-- 5 == 8` and `--5 == 5` are both semantically correct statements and evaluate to `True`.

* Given that `a` is a number, `++a` and `--a` are both valid Python statements but don't behave the same way as compared with similar statements in languages like C, C++, or Java.
  ```py
  >>> a = 5
  >>> a
  5
  >>> ++a
  5
  >>> --a
  5
  ```

  **üí° Explanation:**
  + There is no `++` operator in Python grammar. It is actually two `+` operators.
  + `++a` parses as `+(+a)` which translates to `a`. Similarly, the output of the statement `--a` can be justified.
  + This StackOverflow [thread](https://stackoverflow.com/questions/3654830/why-are-there-no-and-operators-in-python) discusses the rationale behind the absence of increment and decrement operators in Python.

* You must be aware of the Walrus operator in Python. But have you ever heard about *the space-invader operator*?
  ```py
  >>> a = 42
  >>> a -=- 1
  >>> a
  43
  ```
  It is used as an alternative incrementation operator, together with another one
  ```py
  >>> a +=+ 1
  >>> a
  >>> 44
  ```
  **üí° Explanation:** This prank comes from [Raymond Hettinger's tweet](https://twitter.com/raymondh/status/1131103570856632321?lang=en). The space invader operator is actually just a malformatted `a -= (-1)`. Which is equivalent to `a = a - (- 1)`. Similar for the `a += (+ 1)` case.
  
* Python has an undocumented [converse implication](https://en.wikipedia.org/wiki/Converse_implication) operator. 
     
     ```py
     >>> False ** False == True
     True
     >>> False ** True == False
     True
     >>> True ** False == True
     True
     >>> True ** True == True
     True
     ```

     **üí° Explanation:** If you replace `False` and `True` by 0 and 1 and do the maths, the truth table is equivalent to a converse implication operator. ([Source](https://github.com/cosmologicon/pywat/blob/master/explanation.md#the-undocumented-converse-implication-operator))
     
* Since we are talking operators, there's also `@` operator for matrix multiplication (don't worry, this time it's for real).

     ```py
     >>> import numpy as np
     >>> np.array([2, 2, 2]) @ np.array([7, 8, 8])
     46
     ```

     **üí° Explanation:** The `@` operator was added in Python 3.5 keeping the scientific community in mind. Any object can overload `__matmul__` magic method to define behavior for this operator.

* From Python 3.8 onwards you can use a typical f-string syntax like `f'{some_var=}` for quick debugging. Example,
    ```py
    >>> some_string = "wtfpython"
    >>> f'{some_string=}'
    "some_string='wtfpython'"
    ``` 

* Python uses 2 bytes for local variable storage in functions. In theory, this means that only 65536 variables can be defined in a function. However, python has a handy solution built in that can be used to store more than 2^16 variable names. The following code demonstrates what happens in the stack when more than 65536 local variables are defined (Warning: This code prints around 2^18 lines of text, so be prepared!):
     
     ```py
     import dis
    exec("""
    def f():
        """ + """
        """.join(["X" + str(x) + "=" + str(x) for x in range(65539)]))

    f()

    print(dis.dis(f))
    ```
     
* Multiple Python threads won't run your *Python code* concurrently (yes, you heard it right!). It may seem intuitive to spawn several threads and let them execute your Python code concurrently, but, because of the [Global Interpreter Lock](https://wiki.python.org/moin/GlobalInterpreterLock) in Python, all you're doing is making your threads execute on the same core turn by turn. Python threads are good for IO-bound tasks, but to achieve actual parallelization in Python for CPU-bound tasks, you might want to use the Python [multiprocessing](https://docs.python.org/2/library/multiprocessing.html) module.

* Sometimes, the `print` method might not print values immediately. For example,

     ```py
     # File some_file.py
     import time
     
     print("wtfpython", end="_")
     time.sleep(3)
     ```

     This will print the `wtfpython` after 3 seconds due to the `end` argument because the output buffer is flushed either after encountering `\n` or when the program finishes execution. We can force the buffer to flush by passing `flush=True` argument.

* List slicing with out of the bounds indices throws no errors
  ```py
  >>> some_list = [1, 2, 3, 4, 5]
  >>> some_list[111:]
  []
  ```

* Slicing an iterable not always creates a new object. For example,
    ```py
    >>> some_str = "wtfpython"
    >>> some_list = ['w', 't', 'f', 'p', 'y', 't', 'h', 'o', 'n']
    >>> some_list is some_list[:] # False expected because a new object is created.
    False
    >>> some_str is some_str[:] # True because strings are immutable, so making a new object is of not much use.
    True
    ```

* `int('Ÿ°Ÿ¢Ÿ£Ÿ§Ÿ•Ÿ¶ŸßŸ®Ÿ©')` returns `123456789` in Python 3. In Python, Decimal characters include digit characters, and all characters that can be used to form decimal-radix numbers, e.g. U+0660, ARABIC-INDIC DIGIT ZERO. Here's an [interesting story](http://chris.improbable.org/2014/8/25/adventures-in-unicode-digits/) related to this behavior of Python.

* You can separate numeric literals with underscores (for better readability) from Python 3 onwards.

     ```py
     >>> six_million = 6_000_000
     >>> six_million
     6000000
     >>> hex_address = 0xF00D_CAFE
     >>> hex_address
     4027435774
     ```

* `'abc'.count('') == 4`. Here's an approximate implementation of `count` method, which would make the things more clear
  ```py
  def count(s, sub):
      result = 0
      for i in range(len(s) + 1 - len(sub)):
          result += (s[i:i + len(sub)] == sub)
      return result
  ```
  The behavior is due to the matching of empty substring(`''`) with slices of length 0 in the original string.

---
---

# ƒê√≥ng g√≥p

B·∫°n c√≥ th·ªÉ ƒë√≥ng g√≥p cho wtfpython theo nh·ªØng c√°ch d∆∞·ªõi ƒë√¢y

- Cho ch√∫ng t√¥i bi·∫øt nh·ªØng v√≠ d·ª• m·ªõi
- D·ªãch wtfpython sang c√°c ng√¥n gnuwx kh√°c (Xem t·∫°i [issues labeled translation](https://github.com/satwikkansal/wtfpython/issues?q=is%3Aissue+is%3Aopen+label%3Atranslation))
- Minor corrections like pointing out outdated snippets, typos, formatting errors, etc.
- S·ª≠a c√°c l·ªói ph·ª• kh√°c nh∆∞ c√°c ƒëo·∫°n m√£ b·ªã l·ªói th·ªùi, c√°c l·ªói c√∫ ph√°p, l·ªói ƒë·ªãnh d·∫°ng, v√¢n v√¢n.
- Identifying gaps (things like inadequate explanation, redundant examples, etc.)
- T√¨m nh·ªØng thi·∫øu s√≥t (v√≠ d·ª• nh∆∞ gi·∫£i th√≠ch ch∆∞a c·∫∑n k·∫Ω, c√°c v√≠ d·ª• kh√¥ng c·∫ßn thi·∫øt, v√¢n v√¢n.)
- B·∫•t c·ª© ƒë·ªÅ xu·∫•t s√°ng t·∫°o n√†o c≈©ng l√†m cho wtfpython th√∫ v·ªã v√† h·ªØu d·ª•ng h∆°n

Please see [CONTRIBUTING.md](/CONTRIBUTING.md) for more details. Feel free to create a new [issue](https://github.com/satwikkansal/wtfpython/issues/new) to discuss things.

PS: Please don't reach out with backlinking requests, no links will be added unless they're highly relevant to the project.

# L·ªùi c√°m ∆°n

√ù t∆∞·ªüng v√† thi·∫øt k·∫ø c·ªßa wtfpython l·∫•y c·∫£m h·ª©ng t·ª´ d·ª± √°n tuy·ªát v·ªùi c·ªßa Denys Dovhan's [wtfjs](https://github.com/denysdovhan/wtfjs). C√πng v·ªõi ƒë√≥ l√† s·ª± h·ªó tr·ª£ tuy·ªát v·ªùi c·ªßa nh·ªØng ng∆∞·ªùi y√™u Python, gi√∫p cho wtfpython c√≥ ƒë∆∞·ª£c nh∆∞ ng√†y h√¥m nay.

#### M·ªôt v√†i li√™n k·∫øt hay kh√°c!
* https://www.youtube.com/watch?v=sH4XF6pKKmk
* https://www.reddit.com/r/Python/comments/3cu6ej/what_are_some_wtf_things_about_python
* https://sopython.com/wiki/Common_Gotchas_In_Python
* https://stackoverflow.com/questions/530530/python-2-x-gotchas-and-landmines
* https://stackoverflow.com/questions/1011431/common-pitfalls-in-python
* https://www.python.org/doc/humor/
* https://github.com/cosmologicon/pywat#the-undocumented-converse-implication-operator
* https://www.codementor.io/satwikkansal/python-practices-for-efficient-code-performance-memory-and-usability-aze6oiq65
* https://github.com/wemake-services/wemake-python-styleguide/search?q=wtfpython&type=Issues
* WFTPython discussion threads on [Hacker News](https://news.ycombinator.com/item?id=21862073) and [Reddit](https://www.reddit.com/r/programming/comments/edsh3q/what_the_fck_python_30_exploring_and/).

# üéì License

[![WTFPL 2.0][license-image]][license-url]

&copy; [Satwik Kansal](https://satwikkansal.xyz)

[license-url]: http://www.wtfpl.net
[license-image]: https://img.shields.io/badge/License-WTFPL%202.0-lightgrey.svg?style=flat-square

## Chia s·∫ª cho b·∫°n b√®!

N·∫øu b·∫°n th√≠ch wtfpython, b·∫°n c√≥ th·ªÉ chia s·∫ª c√°c li√™n k·∫øt d∆∞·ªõi ƒë√¢y cho b·∫°n b√®,

[Twitter](https://twitter.com/intent/tweet?url=https://github.com/satwikkansal/wtfpython&text=If%20you%20really%20think%20you%20know%20Python,%20think%20once%20more!%20Check%20out%20wtfpython&hashtags=python,wtfpython) | [Linkedin](https://www.linkedin.com/shareArticle?url=https://github.com/satwikkansal&title=What%20the%20f*ck%20Python!&summary=If%20you%20really%20thing%20you%20know%20Python,%20think%20once%20more!) | [Facebook](https://www.facebook.com/dialog/share?app_id=536779657179021&display=page&href=https%3A%2F%2Fgithub.com%2Fsatwikkansal%2Fwtfpython&quote=If%20you%20really%20think%20you%20know%20Python%2C%20think%20once%20more!)  

## B·∫°n c√≥ c·∫ßn b·∫£n pdf c·ªßa wtf hay kh√¥ng?

I've received a few requests for the pdf (and epub) version of wtfpython. You can add your details [here](https://satwikkansal.xyz/wtfpython-pdf/) to get them as soon as they are finished.

T√¥i nh·∫≠n ƒë∆∞·ª£c m·ªôt v√†i y√™u c·∫ßu cho phi√™n b·∫£n pdf (v√† epub) c·ªßa wtfpython. N·∫øu b·∫°n mu·ªën, b·∫°n c√≥ th·ªÉ th√™m th√¥ng tin chi ti·∫øt c·ªßa m√¨nh ·ªü ƒë√¢y [here](https://satwikkansal.xyz/wtfpython-pdf/) ƒë·ªÉ c√≥ phi√™n b·∫£n pdf s·ªõm nh·∫•t.

**That's all folks!** For upcoming content like this, you can add your email [here](https://www.satwikkansal.xyz/content-like-wtfpython/).

*PS: On a sidenote, consider donating a dollar to [plant a tree](https://teamtrees.org/).*
